- setup.cfg
Remove `universal=1` option, from `bdist_wheel` options.
When enabled, it produces incorrect `py2.py3` wheel distribution tag.
Incorrect: `ansible_events-0.4.0-py2.py3-none-any.whl`
Correct:   `ansible_events-0.4.0-py3-none-any.whl`
> Fix inaccurate wheel tag

- ansible_events/cli.py
The `loop.run_in_executor()` method returns a Future.
There is no need to additionally create a wrapper task
that only waits for it.
> Drop `await_future` utility function

- tox.ini
Tox requires an isolated build to use PEP 517 build-backend
> fix tox configuration to support PEP 517 build-backend

- tests/test_engine.py
The `pytest-asyncio` package provides the `event_loop` fixture,
which has `function` scope, which means a new event loop
is already created for each test function.
> Remove `new_event_loop` fixture from `test_engine.py`

- docs/conf.py
- docs/index.rst
Fix warnings:
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
docs/index.rst:2: WARNING: Title underline too short.
Welcome to ansible-events's documentation!
======================================
docs/index.rst:4: WARNING: toctree contains reference to nonexisting document 'modules'
> Fix documentation issues

- .github/workflows/linters.yml
- ansible_events/event_filters/json_filter.py
- ansible_events/inventory.py
- requirements_dev.txt
- requirements_lint.txt
- tests/event_filters/json_filter.py
- tests/sources/log_scraper.py
Fix warnings introduced by installing new flake8 plugin.
Warnings:
```
./tests/sources/log_scraper.py:15:19: B007 Loop control variable 'loc' not used within the loop body.
If this is intended, start the name with an underscore.
./tests/event_filters/json_filter.py:34:30: B006 Do not use mutable data structures for argument defaults.
They are created during function definition time.
All calls to the function reuse this one instance of that data structure, persisting changes between them.
./tests/event_filters/json_filter.py:34:47: B006 Do not use mutable data structures for argument defaults.
They are created during function definition time.
All calls to the function reuse this one instance of that data structure, persisting changes between them.
./ansible_events/inventory.py:18:9: B007 …
```
> Install flake8-bugbear plugin

- ansible_events/builtin.py
- schema/ruleset_schema.json
Be able to produce the output from ansible-runner with json format. In addition to the feature, which can be requested by users, I will need it for black box testing of the CLI.
> add json_mode option for run_playbook action

- ansible_events/builtin.py
- tests/examples/22_print_events.yml
- tests/examples/26_print_events.yml
- tests/test_examples.py
The print_event action currently only supports a single event and fails when invoked with multiple events. This PR adds support for multiple events.
https://issues.redhat.com/browse/AAP-4829
> Support events in print_event

- ansible_events/builtin.py
- ansible_events/engine.py
- tests/test_rules.py
This would help us when we switch to drools.
Places where we call durable.lang have been changed to lang
> Fixed package name imports

- setup.cfg
When we run flake8 locally we want to be able to skip
the venv and .venv directories.
> Added flake8 config setting

- ansible_events/builtin.py
- tests/examples/27_var_root.yml
- tests/test_examples.py
Redid https://github.com/benthomasson/ansible-events/pull/119
var_root is used to optionally lift up the keys in a nested events
dictionary.
The var_root has been modified to take in a sigle nested key in the form
of a.b.c or or a dictionary of the form old_key:new_key
var_root:
a.b.c: c
x.y.z: z
When we have matching on multiple events from different sources the
event payload could have different keys. The var_root can store the
nested keyname for different payloads and pick them from different
events.
If the var_root has the following dictionary
{
'webhook.payload': 'webhook', 
'kafka.message':'kafka'
}
it can modify the events from
{'events': {'m_0': {'webhook': {'payload': {'url': 'http://www.example.com', 'action': 'merge'}}},
'm_1': {'kafka': {'message': {'topic': 'testing', …
> Support var_root in multi events - 2

- ansible_events/util.py
- tests/examples/28_right_side_condition_template.yml
- tests/test_examples.py
Fixes https://issues.redhat.com/browse/AAP-5176
There is no need to use dpath since jinja render can get the data from dicts with dot notation. In this way we add real support to jinja templates in the right side on the condition including jinja filters and arithmetic operations.
> improve jinja support and fix AAP-5176

- Dockerfile
Seems that ubi9 image is not compatible with apple M1 processors. 
https://access.redhat.com/solutions/6833751
https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#
As ubi8 still have support, we can use it until have a fixed ubi9 image. 
Also added missing dependencies required by the collection
> downgrade docker image to ubi8 and add collection dependencies

- ansible_events/drools/durable_rules_engine.py
- ansible_events/drools/jpy_durable_rules_engine.py
- ansible_events/drools/rest_durable_rules_engine.py
Refactored `durable_rules_engine.py`:
- Moved rest-related code to `rest_durable_rules_engine.py`
- Added jpy-related code to `rest_durable_rules_engine.py`
The alternative backend can be conditionally activated by setting the following environment variables:
```
RULES_ENGINE=drools
ANSIBLE_EVENTS_DROOLS_JPY_CLASSPATH=<path-to-jar>
```
~~I had to expose some additional methods in the Java layer. We'll probably want to further iterate over this as we are now invoking some APIs that are not meant for external consumption.~~
EDIT I have just merged 5e5d8b743278c3ecfd62c103910039c1c4058f02 to hide the internals, but this depends on https://github.com/mariofusco/drools-yaml-rules/commit/d94c1240afd84945bfad06d1170f84f906b173d5 -- you should find the jar here …
> Drools Support: Alternative execution flow via `jpy`

- ansible_events/builtin.py
- tests/examples/29_run_module.yml
- tests/examples/30_run_module_missing.yml
- tests/examples/31_run_module_missing_args.yml
- tests/examples/32_run_module_fail.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-5084
- Modules can only be part of collection
- Module args can be passed in via module_args
e.g.
```
action:
run_module:
name: ansible.builtin.debug
module_args:
msg: fred
```
> [AAP-5084] Add support for executing ansible modules as part of action

- ansible_events/builtin.py
- schema/ruleset_schema.json
- tests/examples/33_run_playbook_retry.yml
- tests/examples/34_run_playbook_retries.yml
- tests/playbooks/fail_and_succeed.yml
- tests/test_examples.py
Add option `retry: True` to rerun a playbook once on failure,
or `retries: <count>` to retry multiple times until succeed.
Option `delay: <seconds>` to pause a few seconds before rerun.
The same options can be applied to rerun a module.
See tests/examples/33_run_playbook_retry.yml or
tests/examples/34_run_playbook_retries.yml or
tests/examples/32_run_module_fail.yml for examples.
Resolves: AAP-5126
> [AAP-5126] Allow to rerun a playbook on failure

- ansible_events/rule_generator.py
- tests/rules/test_host_rules.yml
- tests/rules/test_rules.yml
- tests/rules/test_rules_multiple_hosts.yml
- tests/test_conditions.py
To check if an object.attribute exists use **is defined**
e.g
event.j is defined
This aligns us with the Ansible Playbook syntax.
> Removed + syntax of is defined

- ansible_events/builtin.py
- ansible_events/engine.py
Add activation event id and run_at timestamp to the event in the event queue.
Whenever EDA server receives such events, these new added information will help to determine the corresponding rulesets/rules and populate audit rules table with needed information.
Resolves: [AAP-5417](https://issues.redhat.com/browse/AAP-5417)
> Add activation id and run_at timestamp to the event in event queue

- setup.cfg
This PR:
- ensures `pyparsing >= 3.0` is installed as a requirement, see https://github.com/pyparsing/pyparsing/blob/master/docs/whats_new_in_3_0_0.rst#2api-changes 
- closes #179 
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>
> require pyparsing >= 3.0

- ansible_rulebook/builtin.py
Set ansible-runner option rotate_artifacts=1. This will keep only one artifacts folder under the ansible runner working folder. Since we create one temporary working folder for each firing of playbook action, adding this option has no side effect to normal situation. It is useful when retries option is configured for the action. It will automatically remove the artifacts folder for previous failed running and only preserve the latest artifacts.
Replaces #177
> Limit to one artifacts folder for each playbook run

- ansible_rulebook/builtin.py
- ansible_rulebook/engine.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_types.py
- tests/test_examples.py
- tests/test_rules.py
Add more job related details to the event queue, so EDA server side can save them for either debug or job rerun.
Resolves: [AAP-5081](https://issues.redhat.com/browse/AAP-5081)
> Add job details for eda-server usage

- ansible_rulebook/builtin.py
Fix a bug that log is not printed if retry has no delay.
> Always log each retry

- ansible_rulebook/engine.py
- docs/rules.rst
- tests/examples/28_right_side_condition_template.yml
- tests/test_examples.py
If we use the Jinja style substition in a condition we loose the data type. If we get variables from the user via the command line --variables we can set them as a fact in the rule engine and use fact. prefix to access it.
https://issues.redhat.com/browse/AAP-6342
This doesn't work in durable rules since in durable rules the assert_fact doesn't save the fact for later use. If the fact is not used its discarded. And in our case we are comparing an event and a fact in the same condition and we can't assert a fact and an event in the same call to satisfy durable rules conditions.
> [AAP-6342] Don't use {{ }} in conditions

- docs/sources.rst
- tests/sources/template.py
Add instructions how to develop and distribute custom plugins.
Resolves AAP-6239: Docs: ansible-rulebook event source plugin development
> [AAP-6239] Add document for sources

- ansible_rulebook/builtin.py
Fix job event log to use new key of `ansible_rulebook_id`
> Replace ansible_events_id with ansible_rulebook_id for job event

- .github/workflows/tests.yml
- docs/installation.rst
- setup.cfg
- tox.ini
Reverts https://github.com/ansible/ansible-rulebook/pull/208
According to a recent conversation with @benthomasson has been decided to support python 3.8
Includes: 
- Update minimal version in setup and docs
- Update GH action to run supported versions. Fix engine envvar
- Update tox
> Decrease python minimal version to 3.8

- ansible_rulebook/engine.py
- tests/rules/test_combine_hosts.yml
- tests/test_engine.py
- tests/test_examples.py
Run the same playbook only once based on multiple events in a
configurable time window through environmental variable
RUN_PLAYBOOK_DELAY (seconds). Combine hosts collected from all
related events.
Resolves AAP-4436: Combine the same action together on multiple hosts
based on multiple events in a certain period of time
This work only places run_playbook actions into the combinable queue. Technically all other actions can be treated the same way, but I feel there is no need since they are all quick actions. The only exception is the run_module action which can be easily handled the same way after the review.
depends on #202 
replaces #159
> [AAP-4436] Combine the same playbook on multiple hosts

- .github/workflows/tests.yml
- ansible_rulebook/cli.py
- setup.cfg
- tox.ini
Enable drools engine for python 3.11
Close https://issues.redhat.com/browse/AAP-7116
> AAP-7116 Enable drools for python 3.11

- requirements_lint.txt
There is a new release of flake (6.0.0) that seems is not parsing correctly the comment in the setup.cfg, causing all our tests to fail. This PR pin the version to the most recent working version.
> Pin flake8 version

- .github/workflows/tests.yml
Galaxy requests are rate limited by IP causing error in our GH action. This PR change the installation method to use the source code instead the public galaxy repository.
> Move collection installation to repository for GH action

- ansible_rulebook/websocket.py
The websockets library will print connection failure and retry messages at INFO level through the provided logger.
Resolves AAP-6564: ansible-rulebook doesn't handle wrong websocket servers
> Set logger for websocket connect

- ansible_rulebook/builtin.py
Fixed this error
```
DeprecationWarning: The dpath.util package is being deprecated. All util
functions have been moved to dpath package top level
```
> Fixed deprecation warning for dpath

- ansible_rulebook/cli.py
I really believe this print is completely useless for the "--version" flag, it generates a new uuid each time is executed. It has no relation with the version and confuses everybody.
> Remove uuid print in --version flag

- .github/workflows/tests.yml
- ansible_rulebook/cli.py
- ansible_rulebook/util.py
- tests/unit/test_cli.py
- tox.ini
Closes https://issues.redhat.com/browse/AAP-7680
This command with the extended info can be used in issue template and contributing guides to provide a better info.
Taking as reference the `ansible --version` command
Also fixes the flake version when running it through tox. 
Also adds `-vv` flag to pytest to have the complete output in case of test fail. 
How to test: run `ansible-rulebook --version`
Expected output
```
__version__ = '0.9.4'
Executable location = /home/alex/repos/redhat/ansible/eda/ansible-rulebook/venv/bin/ansible-rulebook
Rules engine = durable_rules
Drools_jpy version = 0.1.1
Java home = /usr/lib/jvm/java-17-openjdk-17.0.3.0.7-1.fc34.x86_64
Java version = openjdk 17.0.3 2022-04-19
Python version = 3.9.13 (main, May 18 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat …
```
> AAP-7680 add more info to --version flag

- ansible_rulebook/engine.py
- tests/test_engine.py
- tests/test_examples.py
There is no need to add empty ProcessedEvent to event_log for events that do not match any rules.
Resolves AAP-6141
Type `ProcessedEvent`, `EmptyEvent`, `MessageNotHandled` are not processed by eda-server at all. In theory we could stop sending these event-log completely. Open for discussion.
We could also added an ENV to preserve the feature of adding a ProcessedEvent for every event like before as discussed in [AAP-6141](https://issues.redhat.com/browse/AAP-6141). Is there any use for such event log?
> Do not send ProcessedEvent for unmatched events

- .github/workflows/tests.yml
- pytest.ini
- tests/e2e/conftest.py
- tests/e2e/files/inventories/default_inventory.yml
- tests/e2e/files/playbooks/print_event.yml
- tests/e2e/files/rulebooks/operators/test_eq_operator_int.yml
- tests/e2e/files/rulebooks/operators/test_eq_operator_str.yml
- tests/e2e/files/rulebooks/operators/test_ge_operator.yml
- tests/e2e/files/rulebooks/operators/test_gt_operator.yml
- tests/e2e/files/rulebooks/operators/test_is_defined_operator_int.yml
- tests/e2e/files/rulebooks/operators/test_is_defined_operator_nested.yml
- tests/e2e/files/rulebooks/operators/test_is_defined_operator_str.yml
- tests/e2e/files/rulebooks/operators/test_le_operator.yml
- tests/e2e/files/rulebooks/operators/test_lt_operator.yml
- tests/e2e/files/rulebooks/operators/test_ne_operator_int.yml
- tests/e2e/files/rulebooks/operators/test_ne_operator_str.yml
- tests/e2e/files/rulebooks/operators/test_not_defined_operator.yml
- tests/e2e/files/rulebooks/operators/test_not_defined_operator_nested.yml
- tests/e2e/test_operators.py
- tests/e2e/utils.py
- tests/run_examples.sh
- tests/sources/nested.py
- tests/sources/range.py
1st delivery of the e2e test suite. Includes:
- CLI tests for basic usage of operators. Most of them are currently marked as XFAIL due to found bugs.
- Logging conf for pytest. 
- Little improvement for nested and range plugins
- Convenient simple bash script to run manually the rulebook in examples. 
Closes AAP-7205
> AAP-7205 add e2e tests for operators

- CONTRIBUTING.rst
- Dockerfile
- docs/installation.rst
- tox.ini
Closes [AAP-7759](https://issues.redhat.com/browse/AAP-7759). Removing all references to this env var since we no longer need to force compilation of JPY from source.
> Removing PIP_NO_BINARY env var

- ansible_rulebook/engine.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_types.py
Too many attributes were being called **queue**. Renaming one of the **queue** attributes to **source_queue** to indicate that it is used for sources.
> Refactor: Change an attribute name

- ansible_rulebook/engine.py
We have a single plan queue per Ruleset, where all rules can queue their Actions. The rule engines gives us back the event data when a rule is triggered, we don't need to separate every event into a separate asyncio.Queue.
> Don't create an asyncio.Queue for every event coming in

- ansible_rulebook/condition_parser.py
- ansible_rulebook/condition_types.py
- ansible_rulebook/json_generator.py
- docs/rules.rst
- tests/examples/40_in.yml
- tests/examples/41_not_in.yml
- tests/examples/42_contains.yml
- tests/examples/43_not_contains.yml
- tests/examples/44_in_and.yml
- tests/examples/45_in_or.yml
- tests/test_ast.py
- tests/test_examples.py
Added support for
* in
* not in
* contains
* not contains
https://issues.redhat.com/browse/AAP-7647
e.g.
1. event.mylist contains "alert"
2. event.name in ["alert","warning"]
3. event.name not in ["error","warning"]
4. event.mylist not contains "error"
This is a Drools only feature and wont work with durable rules
> [AAP-7647] Support for in and contains in condition

- ansible_rulebook/engine.py
This helps to prevent cpu peg
https://issues.redhat.com/browse/AAP-7918
> Set a small default number for EDA_RUN_PLAYBOOK_MAX_DELAY

- ansible_rulebook/engine.py
The Rule engine in certain cases will trigger a rule match without any events. We have seen this with a single condition
- condition: event.xyz is not defined
https://issues.redhat.com/browse/AAP-7240
> [AAP-7240] Handle null events from the rule engine

- docs/rules.rst
A fact and an event can't be compared in a simple condition. The fact has to be first assigned to a temporary events field. Then the saved events field can be compared with the event. e.g.
```
condition:
all:
- facts.first << fact.custom.expected_index is defined
- event.i == facts.first.custom.expected_index
```
Previously you could do this
```
condition: event.i == fact.custom.expected_index
```
The simple single condition syntax cannot be used for comparing event and fact anymore.
This change was introduced in
https://github.com/ansible/ansible-rulebook/commit/eb4110b1eaadd64e3972661a4d0ca6921143208b
But the document was not fixed.
This PR fixes the documentation
> Fixed the example of how to use fact and events

- tests/examples/47_generic_plugin.yml
- tests/sources/generic.py
- tests/test_examples.py
Since we support different data types integer, boolean we need something that allows us to put different data types in the payload for comparison in conditions. The current "range" plugin only works with integers, and some of the old tests use the range plugin in the rulebook but put custom payload in the tests. I would like to convert all those test cases to use the generic plugin and put the payload directly into the rulebook.
> Add a generic source plugin for tests

- setup.cfg
asyncio is included in Python3 and we don't have to add it as an external dependency
> Remove asyncio from required dependencies

- tests/e2e/files/rulebooks/hello_events_with_var.yml
- tests/e2e/files/rulebooks/malformed_rulebook.yml
- tests/e2e/test_runtime.py
Closes [AAP-5333](https://issues.redhat.com/browse/AAP-5333). Adding test case to validate correct return codes after program execution.
- Successful RC
- Failed RC due to non-existent inventory
- Failed RC due to bad variable
- Failed RC due to poorly formatted rulebook
> AAP-5333 - Adding test to verify correct return codes

- tests/e2e/test_operators.py
- tests/e2e/test_runtime.py
- tests/e2e/test_websocket.py
Increase the timeout of e2e tests to avoid occasional failures due to GH actions performance. 
In next iterations we will implement other improvements to reduce the time execution of some tests.
> Increase timeout of e2e tests

- tests/sources/generic.py
For timer based tests we would like to be able to put timestamps in the events to aid in debugging
Added an optional boolean arg called "timestamp", if set to true we put a timestamp in the event
> Generic source plugin supports optional timestamps

- tests/sources/generic.py
Added the following options
- **startup_delay** : nnn How long to wait before the plugin starts putting events into the queue. Default 0
- **shutdown_after** : nnn How long to wait before the plugin shutsdown specified in seconds. Default 0
- **repeat_count**   : nnn The number of times each event in the payload should be repeated. Default 1
- **repeat_delay**   : nnn How long to wait before repeating events. Default 0
- **event_delay**    : nnn How loing to wait before sending the next event in the payload. Default 0
- **display**        : True|False   print the event being injected. Default False
If the payload say contains two events [e1, e2]
The repeat_count=2 and repeat_delay allows you to do [e1,sleep(repeat_delay),e1,sleep(repeat_delay),e2,sleep(repeat_delay),e2,sleep(repeat_delay)] …
> Add more options to generic source plugin for time based tests

- ansible_rulebook/builtin.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/actions.rst
- tests/examples/48_echo.yml
- tests/test_examples.py
The debug/print_event have lot of information and don't allow for terse messages. This becomes difficult to comprehend when we have multiple conditions in a rule, which match multiple events. When doing a demo instead of seeing a lot of attributes flow by we can echo terse messages along with a time stamp. The timestamp allows for timer based rules to see if they popped at the expected times.
e.g.
```
- name: r1
condition: event.i == 1
action:
echo:
message: Hurray it works
```
Displays
```
2023-01-13 21:20:47.028365 : Hurray it works
```
> Added a builtin action : echo

- ansible_rulebook/schema/ruleset_schema.json
Fix an issue where JSON schema validation is failing when no source plugin options are defined in a ruleset. This is due to the schema not accepting null types for the additionalProperties key.
Addresses [AAP-7760](https://issues.redhat.com/browse/AAP-7760).
> Fix schema validation for empty additionalProperties

- setup.cfg
Pip doesn't upgrade dependencies in existing installations if there is no a specified version, which can lead to confusion and generate unexpected results since a critical part of the functionality relies on this package. Pinning it we enforce that we are using always the right version of the package.
> Pin drools version

- setup.cfg
Updated setup.cfg to point to the new version
- Support for new temporal AST changes
- The rule engine logs are written to stdout/stderr
> Update to use drools_jpy 0.1.7

- docs/conditions.rst
The default key for the first matching condition is m_0 not m. This was fixed recently in drools to match durable_rules style.
> Fixed typo in conditions document

- ansible_rulebook/app.py
- ansible_rulebook/cli.py
- ansible_rulebook/engine.py
- docs/usage.rst
--print-events allows for the printing of events as they are being read from the source queue.
If --debug is used --print-events is disabled, since --debug logs the event already.
```
ansible-rulebook --inventory ./tests/playbooks/inventory.yml -S ./tests/sources --rulebook rule1.yml --print-events
{   'address': {'city': 'Bedrock', 'state': 'NJ', 'street': '123 Any Street'},
'age': 10,
'name': 'Fred Flintstone'}
Shutdown()
```
> Use cmdline option --print_events

- ansible_rulebook/builtin.py
- ansible_rulebook/engine.py
- tests/test_engine.py
- tests/test_examples.py
1. Use a seperate asyncio task to pull from the plan queue which is independent on pulling from the source queue
2. No longer generate ProcessedEvent in event_log
3. No longer combine hosts when running playbook like actions. Drop the use of EDA_RUN_PLAYBOOK_MAX_DELAY
Resolves AAP-8425
> Refactor how to consume action items from the plan queue

- ansible_rulebook/exception.py
- ansible_rulebook/json_generator.py
- docs/conditions.rst
- tests/examples/51_vars_namespace.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-8470
Allows conditions to contain data from the variables or environment variables passed via --vars or --env-vars
e.g.
```
event.address.street == vars.person.address.street
event.year in vars.person.address.years_active
```
Supports string, integer, floats, booleans, list.
> [AAP-8470] Added support for vars namespace

- ansible_rulebook/engine.py
- ansible_rulebook/json_generator.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/conditions.rst
- docs/development_environment.rst
- pytest.ini
- tests/examples/52_once_within.yml
- tests/examples/53_once_within_multiple_hosts.yml
- tests/examples/54_time_window.yml
- tests/examples/55_not_all.yml
- tests/examples/56_once_after.yml
- tests/examples/57_once_after_multi.yml
- tests/test_examples.py
- Added time constraints in rules schema
- Allow for async communication between Drools and Python
- Added
* Throttle support via
1. once_within
2. once_after
* Time windows for conditions
timeout: nnn seconds
* Not all conditions met in a time window
```
condition:
not_all:
- condition1
- condition2
timeout: nnn seconds 
```
https://issues.redhat.com/browse/AAP-7354
https://issues.redhat.com/browse/AAP-7360
https://issues.redhat.com/browse/AAP-7284
https://issues.redhat.com/browse/AAP-7706
This PR contains examples which can be executed standalone to demonstrate some of these features.
**time window example**
```
ansible-rulebook --inventory ./tests/playbooks/inventory.yml -S ./tests/sources --rulebook tests/examples/54_time_window.yml
```
**not_all example**
```
ansible-rulebook …
```
> Added temporal use cases and handle async responses from Drools

- ansible_rulebook/condition_parser.py
- ansible_rulebook/condition_types.py
- ansible_rulebook/json_generator.py
- docs/conditions.rst
- setup.cfg
- tests/examples/58_string_search.yml
- tests/test_ast.py
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-8433
Support string search in conditions.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tests.html#testing-strings
- match  = pattern for searching in beginning of string
- search = pattern for searching anywhere in string
- regex  = pattern for using regular expression to do search
Updated to latest version of drools
e.g.
```
condition: event.url2 is search("groups/.*/resources/.*")
```
> [AAP-8433] Support for search/match/regex

- ansible_rulebook/engine.py
- ansible_rulebook/json_generator.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/rules.rst
- tests/asts/rules.yml
- tests/asts/rules_with_assignment.yml
- tests/asts/rules_with_assignment2.yml
- tests/asts/rules_with_multiple_conditions.yml
- tests/asts/rules_with_multiple_conditions2.yml
- tests/asts/rules_with_multiple_conditions3.yml
- tests/asts/rules_with_time.yml
- tests/asts/rules_with_timestamp.yml
- tests/asts/rules_with_vars.yml
- tests/asts/rules_without_assignment.yml
- tests/asts/test_filters.yml
- tests/asts/test_host_rules.yml
- tests/asts/test_rules.yml
- tests/asts/test_rules_multiple_hosts.yml
- tests/asts/test_rules_multiple_hosts2.yml
- tests/asts/test_rules_multiple_hosts3.yml
- tests/asts/test_set_facts.yml
- tests/asts/test_simple.yml
- tests/examples/59_multiple_actions.yml
- tests/test_examples.py
- tests/test_rules.py
https://issues.redhat.com/browse/AAP-6465
A rule can have either a single action or a list of actions. If multiple actions are specified they are executed one after the other in the order they are specified in the rulebook. e.g.
```
actions:
- debug:
- print_event:
pretty: true
- echo:
message: "Multiple Action Message1"
- echo:
message: "Multiple Action Message2"
```
> [AAP-6465] Support multiple actions for a rule

- ansible_rulebook/schema/ruleset_schema.json
A rulebook can not contain an empty list of rulesets, update the schema accordingly
closes https://issues.redhat.com/browse/AAP-8681
> AAP-8681 update json schema: rulesets minlength

- ansible_rulebook/condition_parser.py
- ansible_rulebook/condition_types.py
- ansible_rulebook/json_generator.py
We had dropped the use of + for exists and switched to use is defined in PR https://github.com/ansible/ansible-rulebook/pull/151 These are some of the left over related to that.
> Removed dead code

- ansible_rulebook/engine.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_types.py
Renamed an attribute from c to rule_engine_results. The original name was from durable_rules closure object.
> Refactor: change a single letter attribute to descriptive name

- ansible_rulebook/cli.py
Since we delay setting of the log level till we parse the command line drools runs with the root logger settings.
This PR sets the log level for the drools package to be the same as for the ansible-rulebook based on the --verbose or --debug
> Set log level for the drools package

- tests/examples/60_json_filter.yml
- tests/test_examples.py
Need an example to demonstrate how json_filter works We have to exclude all keys with *
and include only those keys that we need. Each level of the key should be a separate array item.
e.g. to pick up key3.key4.f_use* keys each level needs to be listed separately
```
filters:
- ansible.eda.json_filter:
include_keys:
- key3
- key4
- f_use*
exclude_keys:
- "*"
```
> Added example to show how json filter works

- tests/examples/58_string_search.yml
- tests/test_examples.py
To reduce error while writing tests, the source task needs to be cancelled when the test ends. Use the __enter__ and __exit__ methods to ensure that the source task is always cancelled.
> Cleanup test examples

- ansible_rulebook/condition_parser.py
- docs/conditions.rst
- tests/examples/50_negation.yml
- tests/test_examples.py
When using multiple logical statments in a condition with or/and we need ( and ) to resolve ambiguities. Otherwise we should be able to parse simple conditions with a not without braces. The not has a priority over the and and or.
https://issues.redhat.com/browse/AAP-8555
e.g. all of these are valid
```
condition: not event.i == 5
```
```
condition: not event.msg == "Barney"
```
```
condition: not event.j >= 10
```
```
condition: not event.my_boolean
```
But if you use and/or you need surrounding round braces
```
condition: not (event.i > 50 or event.i < 10)
```
> [AAP-8555] Error parsing not condition

- ansible_rulebook/exception.py
- ansible_rulebook/json_generator.py
- tests/test_ast.py
https://issues.redhat.com/browse/AAP-6910
https://issues.redhat.com/browse/AAP-6909
When an assignment is invalid raise an error with the following message
```
event.i << event.nested.i == 1
```
Only events and facts can be used in assignment. event.i is invalid.
We dont support nested vars
```
event.iabc.xyz << event.nested.i == 1
```
event.iabc.xyz is invalid.Valid values start with events or facts. e.g events.var1 or facts.var1 Where var1 can only contain alpha numeric and _ charachters
> [AAP-6910] Report error when assignment is invalid

- tests/examples/40_in.yml
- tests/examples/41_not_in.yml
- tests/examples/42_contains.yml
- tests/examples/43_not_contains.yml
- tests/examples/47_generic_plugin.yml
- tests/examples/48_echo.yml
- tests/test_examples.py
* Some of them were incorrectly using range, switched them to use generic plugin.
* Use the SourceTask to directly run the source for some examples so we don't have to inject the data manually.
> Fix test examples

- tests/examples/27_var_root.yml
- tests/test_examples.py
The current example was using the range plugin and putting dictionary data into the queue. Changed it to use the generic plugin which can insert arbitrary data.
> Changed var root example to use generic plugin

- Dockerfile
- docs/installation.rst
Update installation docs and Dockerfile: after remove durable-rules and using pre-built wheels of jpy some installation steps are outdated. 
Closes: https://issues.redhat.com/browse/AAP-8928
> Update installation docs, remove maven from dockerfile

- tests/test_engine.py
- tests/test_examples.py
The example test_54_time_window fails intermittently, since the test introduces a delay of 10 seconds, the queue get might get the occasional QueueEmpty exception. Attempting to fix it by adding a retry if we get the QueueEmpty exception.
Fixes #346
> Intermittent test failures

- ansible_rulebook/exception.py
- ansible_rulebook/rules_parser.py
- tests/rules/test_blank_ruleset_name.yml
- tests/rules/test_duplicate_ruleset_names.yml
- tests/rules/test_missing_ruleset_name.yml
- tests/test_rules.py
https://issues.redhat.com/browse/AAP-9025
Prevent duplicate, empty ruleset names from being processed
> [AAP-9025] Check for duplicate ruleset names

- ansible_rulebook/engine.py
- ansible_rulebook/util.py
There is a limit of 255 keys in an event payload.
The key size limit was used for durable rules. Now that we have switched to drools we don't have the key count limit
> Removed event key count limits

- ansible_rulebook/engine.py
- docs/conditions.rst
- tests/e2e/files/rulebooks/operators/test_in_str_multiple_extra_vars_operator.yml
- tests/e2e/files/rulebooks/operators/test_not_in_int_extra_vars_operator.yml
- tests/e2e/files/rulebooks/operators/test_not_in_str_extra_vars_operator.yml
- tests/examples/28_right_side_condition_template.yml
- tests/test_examples.py
Since we have the vars namespace for accessing variables passed in from the vars-file or env_vars we don't have to send the vars to the rule engine. The vars are resolved before we send the ruleset to Drools. Added additional notes in documentation.
> Vars related cleanup

- .github/workflows/ci.yml
- .github/workflows/scheduled.yml
Sometimes the upload fails due to outages in codecov. 
- Don't mark the workflow as failed if the upload fails (the job can be executed manually later)
- Add the python version to the flag.
> Fix codecov uploads

- ansible_rulebook/engine.py
hosts defined in this field should overwrite rulebook's hosts field but yield to hosts in event's meta field
Resolves AAP-9218
> [AAP-9218] Honor limit set in run_job_template's job_args.limit field

- pytest.ini
Every mark should be registered in the pytest conf:
```
tests/test_controller.py:32
/home/alex/repos/redhat/ansible/eda/ansible-rulebook/tests/test_controller.py:32: PytestUnknownMarkWarning: Unknown pytest.mark.vcr - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.vcr()
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> Fix msg warning about pytest-vcr

- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/rules.rst
- tests/examples/68_disabled_rule.yml
- tests/test_examples.py
A rule can optionally be disabled by setting enabled=false. This is handy when testing and certain rules need to be disabled temporarily. Fixed the json schema, added an example.
https://issues.redhat.com/browse/AAP-9251
> [AAP-9251] Fixed exclusion of disabled rules

- tests/playbooks/inventory.yml
- tests/test_examples.py
The ansible-playbook was skipping the playbook since none of the hosts matched with this warning.
```
PLAY [Print Hello World and set as fact] ***************************************
skipping: no hosts matched
```
Fixed the event payload to include meta hosts.
> Fix broken test, was missing localhost in events

- ansible_rulebook/cli.py
- docs/usage.rst
- tests/e2e/utils.py
BREAKING CHANGE!
- Remove `debug` and `verbose` flags and add counting mode for logging verbose: `-v = INFO` `-vv = DEBUG`
- Add some missing short flags
- Update docs accordingly
- Update e2e tests accordingly
Closes https://issues.redhat.com/browse/AAP-8086
> Add short flags for CLI and verbose counting mode

- pytest.ini
When the timed use cases fail, the time in the log messages will help in debugging.
> Add log_format and log_date_format in pytest.ini

- ansible_rulebook/builtin.py
- ansible_rulebook/engine.py
- docs/events_and_facts.rst
- tests/e2e/files/rulebooks/actions/test_actions_sanity.yml
- tests/e2e/files/rulebooks/actions/test_run_playbook.yml
- tests/e2e/test_actions.py
Namespace ansible_eda in rulebook is implied. It should never be explictly referenced.
Also process var_root before Jinja substitution.
Resolves AAP-8967
> Only add namespace ansible_eda to extra_vars sent to playbooks

- tests/sources/generic.py
If the payload is empty then skip over it, in some special cases the ruleset might not need any direct events but would be using set_facts to generate the data.
This came about in PR https://github.com/ansible/ansible-rulebook/pull/349 Where there is no payload. 
https://github.com/ansible/ansible-rulebook/blob/3f9793c702401590807b027133c4ca70ec672884/tests/e2e/files/rulebooks/actions/test_run_playbook.yml#L48
This leads to an error in the source
```
2023-02-14 16:38:53,582 - ansible_rulebook.engine - ERROR - Source error
Traceback (most recent call last):
File "/Users/madhukanoor/devsrc/ansible-rulebook/ansible_rulebook/engine.py", line 154, in start_source
await entrypoint(fqueue, args)
File "/Users/madhukanoor/devsrc/ansible-rulebook/tests/e2e/../sources/generic.py", line 97, in main …
```
> Allow for empty payloads in generic source for testing purposes

- ansible_rulebook/builtin.py
- ansible_rulebook/exception.py
When a playbook cannot be found, we throw an index error
```
Traceback (most recent call last):
File "/Users/madhukanoor/devsrc/ansible-rulebook/ansible_rulebook/engine.py", line 522, in execute
await action_method(**action_args)
File "/Users/madhukanoor/devsrc/ansible-rulebook/ansible_rulebook/builtin.py", line 328, in run_playbook
await post_process_runner(
File "/Users/madhukanoor/devsrc/ansible-rulebook/ansible_rulebook/builtin.py", line 635, in post_process_runner
fact_folder = _get_latest_artifact(
File "/Users/madhukanoor/devsrc/ansible-rulebook/ansible_rulebook/builtin.py", line 845, in _get_latest_artifact
return files[0]
IndexError: list index out of range
```
Throw an exception if the runner results file can't be found. Also prevent looking for the facts file when the runner …
> [AAP-9299] Fixes stack trace when a playbook is not found

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/builtin.py
- ansible_rulebook/cli.py
- ansible_rulebook/engine.py
- ansible_rulebook/exception.py
- ansible_rulebook/messages.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/actions.rst
- docs/usage.rst
- tests/e2e/test_actions.py
- tests/examples/36_multiple_rulesets_both_fired.yml
- tests/examples/38_shutdown.yml
- tests/examples/66_sleepy_playbook.yml
- tests/examples/67_shutdown_now.yml
- tests/playbooks/sleeper.yml
- tests/test_engine.py
- tests/test_examples.py
Gracefully handle shutdowns by allowing queued actions to complete. We found issues on ppc64le env where the processes were running slower and leading to actions not getting completed before the Shutdown was getting issued.
There are 2 kinds of Shutdowns
- graceful
- now
A shutdown of kind=graceful, which is the default allows for actions to complete and then ends the processes.
A shutdown of kind=now, doesn't wait for actions to complete and it ends all tasks
We run ansible playbooks using the ansible_runner which has a cancel_callback to cancel a running playbook, when we get a  shutdown, we cancel running playbooks.
https://issues.redhat.com/browse/AAP-9235
--shutdown-delay command line can be used to specify the maximum time in seconds
to wait after a shutdown is issued. The process …
> [AAP-9235] Allow for actions to finish in an ordered shutdown

- tests/e2e/config/default.yml
- tests/e2e/files/rulebooks/actions/test_run_playbook.yml
- tests/e2e/test_actions.py
Depends on #358.
With the introduction of ordered shutdown in PR 358, an intermittent race condition arose with the run_playbook test due to Ruleset 2 bailing before it received the set_fact from ruleset 1. PR 358 adds ordered shutdown, but if there are no pending items in the action queue then the ruleset will end immediately. In this test, once the time specified under `shutdown_after` in ruleset 1 has expired then a shutdown command will be issued to all rulesets, and since ruleset 2 does not have any pending items it will end immediately, sometimes before the `set_fact` from ruleset 1 has had a chance to run. Increasing `shutdown_after` is an option, but this increases the test time unnecessarily. 
This change moves the condition that performs the set_fact so that it occurs at the …
> Fix intermittently failing run_playbook test

- ansible_rulebook/builtin.py
- tests/playbooks/validate_args_playbook.yml
- tests/test_engine.py
We were incorectly passing the playbook name as rulename. Fixed the code to pass in the correct ruleset and rule name.
https://issues.redhat.com/browse/AAP-9610
Fixed the test case to validate the rule name and ruleset name.
> [AAP-9610] Fixed: Pass correct rulename in extra_vars

- ansible_rulebook/rule_set_runner.py
The Drools rule engine maintains stats about the session, when the session ends it returns a dictionary with all the salient stats. This stats is only logged when run in debug or verbose mode (-v or -vv)
```
2023-02-23 11:10:20,309 - ansible_rulebook.rule_set_runner - INFO - {'asyncResponses': 0,
'bytesSentOnAsync': 0,
'end': '2023-02-23T16:10:20.296302Z',
'eventsMatched': 3,
'eventsProcessed': 3,
'eventsSuppressed': 0,
'numberOfRules': 4,
'permanentStorageSize': 0,
'ruleSetName': 'Test actions sanity',
'rulesTriggered': 4,
'sessionId': 1,
'start': '2023-02-23T16:10:17.270232Z'}
```
> To aid in debugging log rule engine stats

- tests/sources/generic.py
We need to use floats for more precision in delays.
> Fix generic plugin to manage delays with floats

- tests/e2e/config/default.yml
- tests/e2e/files/rulebooks/actions/test_actions_sanity.yml
- tests/e2e/test_actions.py
- Add test case for multiple actions
- Inject shutdown after from global config
- Remove range plugin in favor of generic, ensure second ruleset ends as expected
- Asserts with pytest-check
Closes https://issues.redhat.com/browse/AAP-8657
> AAP-8657 sanity test for multiple actions

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/rules_parser.py
- docs/rules.rst
- tests/rules/rule_names_with_substitution.yml
- tests/test_rules.py
https://issues.redhat.com/browse/AAP-8921
Allows for rule names to be substituted from vars passed into ansible-rulebook.
> [AAP-8921] Add support for Jinja2 substitution in rule names

- CHANGELOG.md
- ansible_rulebook/util.py
- tests/e2e/files/rulebooks/operators/test_relational_operators.yml
- tests/examples/72_set_fact_with_type.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-9186
https://jinja.palletsprojects.com/en/3.0.x/nativetypes/ 
Jinja2 support native types if we use NativeTemplate instead of regular template. 
This helps us preserve the data type in action args and source args.
When using native template it uses ast.literal_eval to convert it to native type. This is problematic for us if we blindly send every string into Jinja to evaluate.
```
import ast
x = ast.literal_eval("78")
type(x)
<class 'int'>
```
As shown above it converts integers wrapped as strings into integers which will cause issues for us. So I only pass it to Jinja if the string has a {{ and }} otherwise we don't pass it into jinja for evaluation.
> [AAP-9186] Use NativeTemple in Jinja2 to preserve types

- ansible_rulebook/schema/ruleset_schema.json
- ansible_rulebook/validators.py
As the support for the very old draft-4 was removed from at least
one critical tool (ajv), we switch to draft-7 which also happens to
be the version used by [all the other](https://github.com/ansible/ansible-lint/tree/main/src/ansiblelint/schemas) Ansible related schemas.
Related: https://github.com/ajv-validator/ajv/issues/472
Related: https://github.com/ansible/ansible-lint/issues/3079
Related: https://github.com/ansible/ansible-rulebook/issues/397
> Switch JSON schema to draft-7

- .pre-commit-config.yaml
- ansible_rulebook/schema/ruleset_schema.json
- corrects wrong $id in schema
- adds pre-commit hook that validates schema using ajv library as
in order to prevent future regression. Note that AJV was able to
detect $id bug while python-jsonschema was not.
> Fix $id in schema

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/cli.py
- ansible_rulebook/exception.py
- tests/conftest.py
- tests/test_app.py
https://issues.redhat.com/browse/AAP-8337
Since ansible-rulebook can be used with Automation Controller we don't need to make inventory mandatory. This is needed for the eda-server to launch the ansible-rulebook and execute a job on the Automation Controller.
Check if the rulebook contains any actions with run_module or run_playbook and raise an exception
```
ansible_rulebook.exception.InventoryNeededException: Rule r1 has an action run_playbook which needs inventory to be defined
```
> [AAP-8337] Make inventory optional

- docs/usage.rst
In PR https://github.com/ansible/ansible-rulebook/pull/366 we removed debug and verbose. This PR fixes the leftovers
> Removed references to debug and verbose

- ansible_rulebook/app.py
- ansible_rulebook/builtin.py
- ansible_rulebook/engine.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/util.py
- tests/e2e/files/inventories/default_inventory.ini
- tests/e2e/test_actions.py
- tests/test_engine.py
- tests/test_examples.py
ansible-rulebook doesn't do anything with the inventory data. It just reads it and writes into the inventory file for ansible_runner. So instead of treating every inventory as a yaml file and load it as a dictionary, this PR just loads the inventory data as a blob irrespective of the format and sends it to ansible-runner.
Fixes #241
Closes: https://issues.redhat.com/browse/AAP-7661
> [AAP-7661] Support inventory in ini/yaml formats

- docs/installation.rst
- docs/sources.rst
Docs in the collection were updated which broke these links in the ansible-rulebook docs. Updating the links to point to the base repo.
> Fix broken links to collection

- performance_test/hello_playbook1.yml
The rules.yml rulebook used for performance testing was missing the ansible_eda prefix in the playbook it calls.
Missed from PR # https://github.com/ansible/ansible-rulebook/pull/282
> Performance test playbook was missing the ansible_eda prefix

- CHANGELOG.md
- ansible_rulebook/condition_parser.py
- ansible_rulebook/json_generator.py
- setup.cfg
- tests/test_ast.py
https://issues.redhat.com/browse/AAP-9324
Support identifiers in select and selectattr
upgraded to version 0.2.6 of drools_jpy
> [AAP-9324] Allow for variable names in select

- tests/e2e/files/rulebooks/actions/test_shutdown_graceful.yml
- tests/e2e/files/rulebooks/actions/test_shutdown_now.yml
- tests/e2e/test_actions.py
In PR #440 a fix was implemented to ensure actions in the same rule are executed in sequence. This PR fixes the existing tests that were broken as a result of that PR. There will be a follow up PR to update the actions sanity test to ensure sequential actions are executed in the correct order.
> Update e2e shutdown tests for sequential actions

- ansible_rulebook/app.py
- ansible_rulebook/cli.py
- tests/e2e/test_websocket.py
- tests/unit/test_cli.py
In an earlier fix we had made -r a required parameter which breaks when used in worker mode. In worker mode there is no rulebook the rulebook comes in as a payload on the websocket channel.
Undoes the changes from PR #431
the --id parameter is a string since it can be a GUID. Previously it was an integer
> Fixed worker mode and activation id in parse args

- docs/installation.rst
tested in CentOS Stream 8 and Fedora 37, the folder is called `jre-17-openjdk`, not `java-17-openjdk`
> correct JAVA_HOME for Fedora like systems

- tests/e2e/files/extra_vars/test_variables_extra_vars.yml
- tests/e2e/files/rulebooks/operators/test_logical_operators.yml
- tests/e2e/files/rulebooks/variables/test_variables_sanity.yml
- tests/e2e/test_operators.py
- tests/e2e/test_variables.py
This PR adds coverage for some bugs that were ON_QA.
- AAP-9186: variable type not preserved in set_fact/post_event
- AAP-9325: variables file contains null
- AAP-6910: assignment condition with any/all condition
> Update e2e tests to increase coverage

- ansible_rulebook/collection.py
The new collection layout for ansible.eda has things in different directories under extensions/eda
- The rulebooks moved to extensions/eda/rulebooks
- The event_source moved to extensions/eda/plugins/event_source
- The event_filter moved to extensions/eda/plugins/event_filter
This PR supports the new and the old paths so its going to be backward compatible.
https://issues.redhat.com/browse/AAP-10253
> [AAP-10253] Support new and legacy collection paths

- ansible_rulebook/app.py
- ansible_rulebook/common.py
- ansible_rulebook/exception.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/websocket.py
- tests/test_app.py
- tests/test_websocket.py
1. Handle EndOfResponse Message
2.  Removed Inventory from Payload
3. Make Project Data optional
4. Activation ID is a string
5. Share common args between worker mode and non worker mode
6. Fixed tests
> Fixes handling of activation payload from eda-server

- ansible_rulebook/builtin.py
- ansible_rulebook/job_template_runner.py
1. If in debug mode we will log progress messages otherwise we only report the last status
https://issues.redhat.com/browse/AAP-10248
2. Handles API errors when calling Controller (ControllerAPIException)
3. The run_at date time stamp is compatible with controller it uses the UTC iso8601 with micro seconds
We still would be fetching the job events every 10 seconds since we want to know when the job ends except they won't be sent to the aap server.
> [AAP-10248] Fixed: Running jobs on controller

- CHANGELOG.md
- ansible_rulebook/cli.py
- docs/usage.rst
The controller parameters can also be passed in via env var
* EDA_CONTROLLER_TOKEN
* EDA_CONTROLLER_URL
* EDA_CONTROLLER_SSL_VERIFY (default=yes)
https://issues.redhat.com/browse/AAP-10398
> [AAP-10398] Use env var controller params

- setup.cfg
ansible-rulebook needs dpath at version 2.1.4 or above otherwise it fails with the dpath.get error
> Fixed: inconsistent version of dpath

- CHANGELOG.md
- ansible_rulebook/builtin.py
- ansible_rulebook/engine.py
- ansible_rulebook/event_filters/insert_meta_info.py
- ansible_rulebook/exception.py
- ansible_rulebook/util.py
- docs/filters.rst
- requirements_test.txt
- tests/e2e/test_actions.py
- tests/e2e/test_runtime.py
- tests/e2e/test_websocket.py
- tests/event_filters/test_insert_meta_info.py
- tests/test_engine.py
- tests/test_examples.py
- tests/unit/test_util.py
This builtin filter is added to every source and embellishes the event data with the following meta data
```
{'meta': {'source': {'name': 'my_source',
'type': 'ansible.eda.range'}},
'received_at': '2023-03-23T19:11:15.802274Z',
'uuid': 'eb7de03f-6f8f-4943-b69e-3c90db346edf',
}
```
https://issues.redhat.com/browse/AAP-10473
For internal events coming from set_fact/post_event/retract_fact we set the source name and type to **internal**.
The retract fact is currently broken because of the way Drools decides to delete the fact, since the meta portion never matches it doesn't retract the fact. Some of the tests had to be skipped because of this issue. Talking to the Drools team to see if the retract fact can skip the meta portion when doing a match.
> [AAP-10473] Adds support for calling eda.builtin.insert_meta_info     

- ansible_rulebook/collection.py
In the new ansible.eda collection the
* event_source is called event_sources
* event_filter is called event_filters
Collection PR https://github.com/ansible/event-driven-ansible/pull/108
This PR still says backeard compatible with the old layout.
The singluar form changes were made in https://github.com/ansible/ansible-rulebook/pull/458
> [AAP-10253] Use plural form for filters and sources

- .gitignore
- requirements_test.txt
- tests/e2e/utils/awx/ansible.cfg
- tests/e2e/utils/awx/create-cluster.yml
- tests/e2e/utils/awx/install-awx.yml
- tests/e2e/utils/awx/kind-config.yml
- tests/e2e/utils/awx/readme.md
- tests/e2e/utils/awx/requirements.txt
- tests/e2e/utils/awx/roles/install-awx/defaults/main.yaml
- tests/e2e/utils/awx/roles/install-awx/tasks/main.yaml
- tests/e2e/utils/awx/roles/install-awx/templates/admin-password-secret.yml.j2
- tests/e2e/utils/awx/roles/install-awx/templates/awx.yaml.j2
- tests/e2e/utils/awx/roles/install-awx/templates/kustomization/kustomization.yaml.j2
Provides an easy, relatively fast way to deploy a cluster of k8s + awx for testing. This can be taken from other EDA projects that might require it as well. It's based on kind, a project from the kubernetes community to deploy a cluster for testing in docker, a requirement to run integration tests in Github Actions 
This follows the guide here: https://github.com/ansible/awx-operator/blob/devel/README.md
Closes AAP-10773
> Add utils to deploy k8s + awx in docker/podman for testing

- tests/examples/57_once_after_multi.yml
In the once_after testcase I had the event burst every 15 seconds and the time window was also 15 seconds so once in a while the new event burst would get caught in the earlier time window and get suppressed. Now I have changed the loop delay to 18 seconds so the event burst happens after 18 seconds.
> Fix intermittent test failures

- ansible_rulebook/builtin.py
- tests/test_examples.py
We were setting the status only for external actions like
* run_playbook
* run_module
* run_job_template
Now we have started setting the stats for internal actions like
* none
* debug
* print_event
* set_fact
* post_event
* retract_fact
* shutdown
Once the internal action is executed successfully we set the status to successful
https://issues.redhat.com/browse/AAP-11110
> [AAP-11110] Added status for internal actions

- ansible_rulebook/builtin.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/util.py
- tests/e2e/test_actions.py
A single rule can fire multiple actions, when these actions are sent to the aap-server, it doesn't know if the rule has 1 action or more than 1 actions. The rule_run_at allows us to group all the actions into a single rule. This also helps on the server side since we are capturing when the rule engine, Drools tells us that a rule has matched and we should fire the actions.
> Added rule_run_at to group multiple actions in a single rule

- tests/e2e/files/extra_vars/operator_variables.yml
- tests/e2e/files/rulebooks/operators/test_membership_operators.yml
- tests/e2e/files/rulebooks/operators/test_select_operator.yml
- tests/e2e/files/rulebooks/operators/test_selectattr_operator.yml
- tests/e2e/test_operators.py
Extending test cases to cover scientific notation. Closes [AAP-9362](https://issues.redhat.com/browse/AAP-9362).
> Update e2e tests to use scientific notation

- docs/conditions.rst
Multiple conditions have special handling in Drools which keep the events in cache till they are used and then re-evaluated when the events match.
> Added example of multiple conditions

- ansible_rulebook/collection.py
ansible-galaxy fails in openshift because of the user-changing security scheme because it tries to make a temporary file in a directory that is write protected.  This is a fix to get ansible-galaxy working in openshift by writing the temp files to /tmp.
> Fix ansible-galaxy temp directory when running in openshift.

- CHANGELOG.md
- ansible_rulebook/json_generator.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/conditions.rst
- docs/rulebooks.rst
- setup.cfg
- tests/examples/77_default_events_ttl.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-11350
The Drools default_events_ttl is 2 hours.
Each ruleset can specify its own value and it can
also be overridden at the individual rule level
> [AAP-11350] Added support for default_events_ttl

- CHANGELOG.md
- ansible_rulebook/cli.py
- ansible_rulebook/engine.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/util.py
- docs/usage.rst
- tests/e2e/test_websocket.py
- tests/e2e/utils.py
If ansible-rulebook is invoked with --heartbeat nn, where nn is the seconds to wait between sending heartbeat, it will send session stats about all running ruleset sessions. This allows the server to monitor if the ansible-rulebook is responsive.
The payload coming in has the following structure
```
{'type': 'SessionStats', 
'activation_id': '42',
'stats': {'start': '2023-04-25T17:02:03.736195Z', 'end': '2023-04-25T17:02:04.856004Z', 'numberOfRules': 1, 'numberOfDisabledRules': 0, 'rulesTriggered': 1, 'eventsProcessed': 2000, 'eventsMatched': 1, 'eventsSuppressed': 1999, 'permanentStorageSize': 0, 'asyncResponses': 0, 'bytesSentOnAsync': 0, 'sessionId': 1, 'ruleSetName': 'Test websocket range events'}, 
'reported_at': '2023-04-25T17:02:04.857362Z'}
```
The end is sent only when the …
> [AAP-11337] Send heartbeat on web socket channel

- docs/conditions.rst
wrong indentation in yaml snippet in doc would make it fail to be valid yaml.
Current doc:
After this change:
> fix invalid yaml in doc

- tests/unit/test_cli.py
The tests were failing when Java version: 20
> Fix test failures when java version doesn't have minors

- ansible_rulebook/app.py
- ansible_rulebook/exception.py
- tests/test_app.py
Due to recent changes in the backend, the web socket connection is closed prematurely from the server side leading to a misleading error on the ansible-rulebook side.
With this PR we are logging an error and adding an exception to help the user understand where the issue is.
https://issues.redhat.com/browse/AAP-11677
> [AAP-11677] Fixes web socket connection issues

- docs/conditions.rst
According to my understanding, the `debug:` action schema is defined to accept only `msg` or `var`.
Per the schema:
https://github.com/ansible/ansible-rulebook/blob/5c57c8a59be6a0d9410e06352bfe28dba9d33a76/ansible_rulebook/schema/ruleset_schema.json#L567-L588
Per the `debug:` action doc: 
https://github.com/ansible/ansible-rulebook/blob/5c57c8a59be6a0d9410e06352bfe28dba9d33a76/docs/actions.rst?plain=1#L373-L378
Thus making these changed snippet in the same documentation, invalid.
I'm therefore suggesting correcting the example snippets in the documentation in this PR, according to the schema:
> doc updage debug: action to comply with schema

- ansible_rulebook/builtin.py
- ansible_rulebook/exception.py
- ansible_rulebook/rule_set_runner.py
- tests/test_examples.py
Exception object cannot be serialized and sent through websocket. Catch JobTemplateNotFoundException explicitly
Fixes AAP-11969: ansible-rulebook worker mode fails to handle JobTemplateNotFoundException
> Do not place the whole exception object in event_log

- ansible_rulebook/job_template_runner.py
Fixes AAP-12047: It is not clear when a run_job_template fails due to wrong JT name
> Enhance JobTemplateNotFoundException error message

- docs/conditions.rst
Make the note on conditions.all more visible by making it a warning. 
Also fix the codeblock to be part of the warning/note.
> doc: warn about use of all in conditions

- CHANGELOG.md
- ansible_rulebook/cli.py
- ansible_rulebook/rule_set_runner.py
- docs/usage.rst
Added a new command line option called **--execution-strategy**
* sequential (default)
* parallel
This will help us from overloading the controller when a simple rulebook runs run_job_template with no throttling
This applies to **all actions** not just run_job_template or run_playbook or run_module.
A properly written rulebook that can handling throttling with either once_after or once_within can run things in parallel.
https://issues.redhat.com/browse/AAP-11904
> [AAP-11904] Added execution-strategy command line option to prevent overloading controllers

- ansible_rulebook/rule_set_runner.py
- tests/examples/27_var_root.yml
- tests/test_examples.py
We use callbacks coming from Drools which use a closure to store the action args, that should be immutable since it affects subsequent calls. we were modifying the action_args causing the var_root issue
https://issues.redhat.com/browse/AAP-12374
Fixes #508
> [AAP-12374] Var root was only getting honored for first trigger

- setup.cfg
Drools is logging extra clock times when timer based tests fail intermittently
Switches to 0.3.2 of drools
> Drools changes to debug intermittent test failures

- .github/actions/all-tests/action.yml
- .github/actions/e2e-tests/action.yml
- setup.cfg
- tests/examples/33_run_playbook_retry.yml
- tests/examples/34_run_playbook_retries.yml
- tests/playbooks/fail_and_succeed.yml
- tests/test_engine.py
Upgraded to drools_jpy 0.3.3 which had a missing event 
Fixed code coverage which was getting overwritten
Fixed a test that was using same file name in 2 different tests when run in parallel they used to fail.
https://issues.redhat.com/browse/AAP-12513
Hopefully this fixes the intermittent test failures.
> [AAP-12513] Fix intermittent test failures because of missing events in drools

- tests/e2e/test_websocket.py
Since the stats are sent every 2 seconds its possible that we might have more than 2 stats records we would see
This leads to intermittent failures
https://github.com/ansible/ansible-rulebook/actions/runs/5081433799/jobs/9130122539
> The heartbeat may produce more than 2 stats.

- CHANGELOG.md
- ansible_rulebook/collection.py
- tests/test_collection.py
We were only checking for playbooks in the root directory of the collection. This PR looks for the playbook in the root as well as the playbooks directory
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html
Fixes #514
Supports .yaml or .yml extensions for rulebooks
https://issues.redhat.com/browse/AAP-9191
> In an ansible collection playbooks are in playbooks directory

- CHANGELOG.md
- ansible_rulebook/builtin.py
- ansible_rulebook/schema/ruleset_schema.json
- tests/e2e/test_actions.py
- tests/examples/78_complete_retract_fact.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-11109
We always use partial match but if for some reason the user wants to use a complete match they can set partial : False
> [AAP-11109] Support for complete and partial retract facts

- CHANGELOG.md
- ansible_rulebook/cli.py
- ansible_rulebook/conf.py
- ansible_rulebook/engine.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/rulebooks.rst
- tests/conftest.py
Continuation of PR #506
The rulesets in a rulebook can have an optional attribute called
* execution_strategy = sequential | parallel
Default is sequential
https://issues.redhat.com/browse/AAP-11904
This is still at the ruleset level and can't be configured at the rule level, which is a bit more challenging to implement.
> [AAP-11904] Added execution_strategy for rulesets in rulebooks

- CHANGELOG.md
- ansible_rulebook/rule_set_runner.py
- tests/test_examples.py
When a job template fails we were not supplying the uuid's for rule, ruleset and action causing errors on server side.
The server would discard those actions coming in leading to rule audits missing.
There might be other JIRA issues related to the same error
https://issues.redhat.com/browse/AAP-12529
> [AAP-12529] When an action fails report all required attributes

- CHANGELOG.md
- setup.cfg
https://issues.redhat.com/browse/AAP-12513
Drools was missing triggering rules intermittently New version of drools_jpy 0.3.4
> [AAP-12513] Upgraded to newer version of drools

- CHANGELOG.md
- ansible_rulebook/websocket.py
- tests/test_websocket.py
The websocket connection at times will get disconnected from the server side, when this disconnect happens we miss posting the event. The connection is re-established but the event that was being sent during the disconnect is not resent. This PR addresses this issue.
The logs looks like following:
```
2023-06-07 14:39:19,150 - ansible_rulebook.websocket - WARNING - websocket ws://host.containers.internal:8000/api/eda/ws/ansible-rulebook connection closed
2023-06-07 14:39:19,151 - ansible_rulebook.rule_set_runner - INFO - Task action::run_job_template::Launch storm of JT's with a single action::Run job template - storm mode - single action finished, active actions 0
2023-06-07 14:39:19 151 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.RegisterOnlyAgendaFilter - …
```
> [AAP-12522] Resend the last event when the websocket connection is reconnected

- ansible_rulebook/app.py
- ansible_rulebook/common.py
- tests/test_app.py
At startup once we validate the rulebook for actions if there is an action called run_job_template, we will validate the connection to the controller.
https://issues.redhat.com/browse/AAP-13209
> [AAP-13209] Skip connecting to controller if no run_job_template action

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/job_template_runner.py
Using aiohttp sessions we can limit the number of concurrent connections to the controller.
The current limit is 30 connections, it can be changed via an env var EDA_CONTROLLER_CONNECTION_LIMIT
When used in conjunction with execution_stratgey: parallel we should be able to create job requests without overloading the controller and getting a 502.
https://issues.redhat.com/browse/AAP-12600
> [AAP-12600] Limit the number of concurrent connections to controller

- .pre-commit-config.yaml
Our ruleset schema doesn't get autofixed when we make changes to it. This way in the first pass it will complain and fix it and we can git add it after the pre-commit runs
> chore: fix the pre-commit to fix json files

- .pre-commit-config.yaml
- ansible_rulebook/schema/ruleset_schema.json
The pretty-format-json has a default indent of 2 spaces which causes our json file to change completely, set indent to be 4
> chore: for pretty_json indent should be 4 and dont sort keys

- tools/convert_to_ast.py
ansible-rulebook internally uses code to convert a rulebook from yml format to a Abstract Syntax Tree (ast) format. This AST is then passed into the rule engine. The parsing is done using pyparsing in ansible-rulebook. When writing tests for drools_jpy we need the AST format, since the code is hidden inside ansible-rulebook its not easy to access it. This tool exposes that ast conversion feature so we can convert one rulebook at a time to AST format for testing. If the rulebook has references to vars and env vars they can be passed into the converter since it would substitute the variables in the AST.
usage:
python3 tools/convert_to_ast.py [-h] -r RULEBOOK [-e VARS] [-o OUTPUT] [-E ENV_VARS]
> test: tool to convert rulebook yml to ast format

- docs/decision_environment.rst
Leave the note referencing its potential usage.
> Remove the container init cmd from the default examples

- CHANGELOG.md
There were some errors in the changelog between the 1.0.0 tag and the release. In that week some changes were added as per 1.0.0 wrongly. This PR fixes the changelog moving/adding the changes to 1.0.1
> Fix included changes for 1.0.0 in changelog

- ansible_rulebook/rule_set_runner.py
- tests/e2e/test_websocket.py
[AAP-12987](https://issues.redhat.com/browse/AAP-12987)
Previously we were only sending the session stats on timed intervals and not when a rule gets triggered. This was causing the lag as reported in the ticket. With this PR we are now sending the session stats when a rule fires in addition to the timed intervals.
> fix: send session_stats if heartbeat enabled after a rule is triggered

- CHANGELOG.md
- ansible_rulebook/condition_parser.py
- docs/conditions.rst
- setup.cfg
- tests/e2e/files/rulebooks/operators/test_logical_operators.yml
- tests/e2e/files/rulebooks/operators/test_selectattr_operator.yml
- tests/e2e/test_operators.py
- tests/test_ast.py
work-in-progress as i'm volunteering to work on this e2e, so this is a quite-complete draft for the ansible-rulebook side; i'll keep posted as i will progress on drools-ansible-rulebook-integration side.
EDIT: demonstrate working locally and added e2e test as requested
**JIRA**: https://issues.redhat.com/browse/DROOLS-7475
**referenced Pull Requests**: 
* https://github.com/ansible/ansible-rulebook/pull/539
* https://github.com/ansible/drools_jpy/pull/50
* https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/56
* https://github.com/kiegroup/drools/pull/5333
* https://issues.redhat.com/browse/AAP-10738
* https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/65
* https://github.com/ansible/drools_jpy/pull/51
> AAP-10738 DROOLS-7475 Proposed feature for ['key'] accessor

- CHANGELOG.md
- ansible_rulebook/job_template_runner.py
- tests/test_controller.py
Closes: https://github.com/ansible/ansible-rulebook/issues/554
Jira: https://issues.redhat.com/browse/AAP-14215
> Add trailing slash to config slug in awx client

- tests/examples/27_var_root.yml
- tests/examples/36_multiple_rulesets_both_fired.yml
- tests/examples/42_contains.yml
- tests/examples/43_not_contains.yml
- tests/examples/47_generic_plugin.yml
- tests/examples/49_float.yml
- tests/examples/50_negation.yml
- tests/examples/51_vars_namespace.yml
- tests/examples/52_once_within.yml
- tests/examples/53_once_within_multiple_hosts.yml
- tests/examples/54_time_window.yml
- tests/examples/55_not_all.yml
- tests/examples/56_once_after.yml
- tests/examples/57_once_after_multi.yml
- tests/examples/58_string_search.yml
- tests/examples/60_json_filter.yml
- tests/examples/61_select_1.yml
- tests/examples/62_select_2.yml
- tests/examples/63_selectattr_1.yml
- tests/examples/64_selectattr_2.yml
- tests/examples/65_selectattr_3.yml
- tests/examples/66_sleepy_playbook.yml
- tests/examples/67_shutdown_now.yml
- tests/examples/70_null.yml
- tests/examples/72_set_fact_with_type.yml
- tests/examples/73_mix_and_match_list.yml
- tests/examples/74_self_referential.yml
- tests/examples/75_all_conditions.yml
- tests/examples/76_all_conditions.yml
- tests/examples/77_default_events_ttl.yml
Since we have the generic source plugin in the eda collection we can switch the source to use the one from collection
> test: changed examples to use the ansible.eda.generic

- ansible_rulebook/app.py
In ansible-rulebook 1.0.1 (#538), the connection to the controller was checked only when using the `run_job_template` action.
In ansible-rulebook 1.0.2 (#543), `run_workflow_template` action was added.
This PR allows checking the connection to the controller even when using the `run_workflow_template` action.
> Connecting to controller if run_workflow_template too

- ansible_rulebook/builtin.py
- ansible_rulebook/exception.py
- ansible_rulebook/schema/ruleset_schema.json
- tests/e2e/test_actions.py
- tests/examples/29_run_module.yml
- tests/test_examples.py
Wraps the module into a playbook and runs the playbook via ansible runner. This gives us the ability to get the module output.
https://issues.redhat.com/browse/AAP-14735
The following is a sample wrapper for a module, the module_args can be a string or it can be a dictionary.
```yaml
- gather_facts: false
hosts: all
name: wrapper
tasks:
- ansible.eda.upcase:
name: Fred Flintstone
name: Module wrapper
register: module_result
- ansible.builtin.set_fact:
cacheable: true
module_result: '{{ module_result }}'
name: save result
```
> fix: [AAP-14735] process output from a module

- CHANGELOG.md
- ansible_rulebook/json_generator.py
- ansible_rulebook/rule_types.py
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/rulebooks.rst
- tests/e2e/files/rulebooks/test_match_multiple_rules.yml
- tests/e2e/test_match_multiple_rules.py
- tests/examples/80_match_multiple_rules.yml
- tests/examples/81_match_single_rule.yml
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-9755
https://issues.redhat.com/browse/AAP-13131
Drools has always supported firing of multiple rules when an event or a fact comes in. Durable rules only supported this behavior for facts but not for events. This PR adds a feature to a ruleset to indicate if it should match_multiple rules. The default is false
https://github.com/ansible/ansible-rulebook/assets/6452699/20daa5aa-75c7-4c63-93f0-01678ba4c986
> feat: support firing of multiple rules

- ansible_rulebook/builtin.py
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-15939
The job ui url for workflow template was incorrect it was missing workflow in the path.
e.g. https://<controller_ip>/#/jobs/workflow/3822/details
> fix: workflow_template job url was incorrect

- ansible_rulebook/json_generator.py
- setup.cfg
- tests/e2e/files/rulebooks/82_non_alpha_keys.yml
- tests/e2e/test_non_alpha_keys.py
- tests/examples/82_non_alpha_keys.yml
- tests/test_ast.py
- tests/test_examples.py
https://issues.redhat.com/browse/AAP-16038
Previously we only supported non alpha numeric keys below the root level, so you needed an intermediate node all the time. This fixes that issue.
Needs a new drools_jpy package
> fix: support non alpha numeric keys at root level

- ansible_rulebook/schema/ruleset_schema.json
Every ruleset should have a name so we can post events/facts between them.
> chore: ruleset.name is required parameter

- .github/workflows/build-image.yml
- tests/e2e/test_match_multiple_rules.py
- tests/e2e/test_non_alpha_keys.py
- tests/e2e/test_run_module_output.py
- tests/e2e/test_websocket.py
Some tests in the e2e suite are attempting to bind to ipv6 in the CI pipeline. Switching 'localhost' for '127.0.0.1' to prevent these failures.
Also updating the build-and-push-image CI job to run only if the e2e tests pass.
> fix: failing e2e tests in CI due to ipv6 binding

- tests/e2e/test_match_multiple_rules.py
- tests/e2e/test_non_alpha_keys.py
- tests/e2e/test_run_module_output.py
- tests/e2e/test_websocket.py
Missed to update the 'host' variable, which is used for instantiating the websocket server.
> fix: e2e test ws binding to ipv6

- .pre-commit-config.yaml
- commitlint.config.js
- docs/development_environment.rst
- Disable subject-case: we might use acronyms or jira tickets that will contain uppercase letters. 
- Fix wrong configuration for body length
- Add a dependency to pre-commit
- Extends docs for commitlint with pre-commit
> ci: add more configuration for commitlint

- requirements_test.txt
- tests/e2e/test_non_alpha_keys.py
- tests/test_examples.py
This allows us to link a test to a JIRA ticket.
e.g.
@pytest.mark.jira("AAP-16038")
> chore: add pytest-jira

- .bumpversion.cfg
- the bump2version commit doesn't conform to commitlint hence disabling it
- the tag creation has also been disabled since the tag is created before the PR is merged.
This was discovered when trying to create a 1.0.3 release of the product
> chore: fix bump2version config

- setup.cfg
Add a missing dependency required by https://github.com/ansible/ansible-rulebook/pull/516
Closes: https://github.com/ansible/ansible-rulebook/issues/609
> chore: add missing dependency: watchdog

- CHANGELOG.md
- ansible_rulebook/rules_parser.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/conditions.rst
- tests/examples/83_boolean_true.yml
- tests/test_examples.py
Since rules have a condition if we need the condition to fire everytime for some usecases (like repeater) you can set the condition to true
e.g.
```
rules:
- name: r1
condition: true
action:
print_event:
```
Currently we support this
```
- name: r1
condition: "true == true"
action:
print_event:
```
> feat: allow for explicit boolean in condition

- Dockerfile
When developing new features which involves using newer collection we need access to the collection in the image. When doing a developer build of an image provide a build arg for the name of repo
e.g.
```
podman build --build-arg DEVEL_COLLECTION_LIBRARY=1 --build-arg DEVEL_COLLECTION_REPO=git+https://github.com/mkanoor/event-driven-ansible.git,pg_listener -t localhost/ansible-rulebook:latest .
```
> chore: optionally allow to use a separate collection repo

- ansible_rulebook/action/run_job_template.py
- ansible_rulebook/action/run_playbook.py
- ansible_rulebook/action/run_workflow_template.py
- ansible_rulebook/engine.py
- ansible_rulebook/rule_generator.py
- ansible_rulebook/rule_set_runner.py
We had some messages which were more appropriate as debug rather than info. This reduces some of the noise that gets generated when run with -v option and we have lots of events
> refactor: changed some info to debug

- .github/actions/image-test/action.yml
- Dockerfile
Closes [AAP-15000](https://issues.redhat.com/browse/AAP-15000).
The main changes are switching to Centos stream image and installing ansible-core instead of the full ansible package.
Image size is reduced from ~2gb to ~500mb.
Tests in the eda-qa test suite are passing with this image.
> AAP-15000: Changes to container image to reduce overall size

- docs/rulebooks.rst
gather_facts defaults to false and needs to be set to true in order to interact with facts as this sample does.
> docs: fix rulebooks documentation for missing gather_facts

- Dockerfile
Resolves [ AAP-19015](https://issues.redhat.com/browse/AAP-19015). Fixes the image to set 0775 permissions on the /app directory.
> fix: container image permissions

- Dockerfile
Without git installed, the following error happens when attempting to build:
ERROR! Could not find git executable to extract the collection
> Ensure git is installed when DEVEL_COLLECTION_LIBRARY is used

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/cli.py
- ansible_rulebook/conf.py
- ansible_rulebook/exception.py
- ansible_rulebook/token.py
- ansible_rulebook/websocket.py
- docs/usage.rst
- tests/e2e/utils.py
- tests/test_token.py
- tests/test_websocket.py
The cli expects to receive websocket-access-token, websocket-refresh-token, and websocket-token-address.
It does not send the authentication header if above arguments are not provided, so it works with the old eda-server that does not authenticate incomming websocket connecitons.
Fixes AAP-17776: ansible-rulebook uses token for authentication
> feat: add websocket authentication using jwt token

- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/util.py
- ansible_rulebook/websocket.py
- tests/e2e/test_match_multiple_rules.py
- tests/e2e/test_run_module_output.py
- tests/test_examples.py
- tests/unit/action/test_debug.py
- tests/unit/action/test_run_playbook.py
- tests/unit/action/test_set_fact.py
- tests/unit/action/test_shutdown.py
Both keys will co-exist in the message body sent to eda-server for backward compatibility reason. activation_id will be removed in the future.
Fixes AAP-18855: ansible-rulebook reports activation instance ID as activation ID
> fix: add activation_instance_id alone with activation_id

- CHANGELOG.md
- ansible_rulebook/action/helper.py
- ansible_rulebook/cli.py
- ansible_rulebook/conf.py
- docs/usage.rst
- tests/e2e/test_skip_audit_events.py
- tests/e2e/utils.py
When running source activation in production mode we want to have an option to skip sending of audit events to the server In test mode for source activation like regular activation we need to be able to send audit events
https://issues.redhat.com/browse/AAP-19479
> feat: skip-audit-events option

- tests/e2e/test_run_module_output.py
- tests/e2e/test_skip_audit_events.py
When tests are run in parallel we were getting port conflicts. Since the 2 tests were copied from the websocket tests they used the same port numbers.
We don't see these errors when tests are run serially
E OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 31415): address already in use
> test: fix port conflicts in websocket tests

- ansible_rulebook/websocket.py
- tests/e2e/test_websocket.py
- tests/e2e/utils.py
- tests/test_websocket.py
includes:
- fix: handle unexpected error raised from websocket server (#644)
> sync devel with main

- Dockerfile
- ansible_rulebook/action/helper.py
- ansible_rulebook/action/pg_notify.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/schema/ruleset_schema.json
- setup.cfg
- tests/unit/action/test_pg_notify.py
Added an action to send notifications via postgres LISTEN/NOTIFY
This feature requires an updated ansible.eda collection with the pg_listener source plugin
Using this branch you can create an image with the new collection and push it to your private quay.io repo
* podman login quay.io
* podman build --no-cache --build-arg DEVEL_COLLECTION_LIBRARY=1 --build-arg DEVEL_COLLECTION_REPO=git+https://github.com/mkanoor/event-driven-ansible.git,pg_listener -t quay.io/<your_userid>/ansible-rulebook:latest .
* podman push quay.io/<your_user_id>/ansible-rulebook:latest
This will ensure that your image has the latest collection which can use the pg_listener source plugin in a rulebook.
> feat: added pg_notify

- .github/actions/run-flake/action.yml
- .github/actions/run-isort/action.yml
- .github/workflows/ci.yml
- .github/workflows/scheduled.yml
- .readthedocs.yaml
- Dockerfile
- ansible_rulebook/__init__.py
- docs/contributing.rst
- docs/development_environment.rst
- docs/installation.rst
- setup.cfg
- tox.ini
Make python3.11 the minimal supported version of python, required for incoming features and dependencies.
Jira: https://issues.redhat.com/browse/AAP-19622
> chore: set python3.11 as the minimal supported version

- CHANGELOG.md
- ansible_rulebook/job_template_runner.py
- ansible_rulebook/util.py
- tests/data/awx_test_data.py
- tests/test_controller.py
A controller url like "https://awx-host/awx" is not supported trying the connection against "https://awx-host/[AWX-SLUG]"
Fixes: https://github.com/ansible/ansible-rulebook/issues/652
Jira: https://issues.redhat.com/browse/AAP-19726
> fix: enable base_path for controller url

- CHANGELOG.md
- ansible_rulebook/job_template_runner.py
- ansible_rulebook/util.py
- tests/data/awx_test_data.py
- tests/test_controller.py
A controller url like "https://awx-host/awx" is not supported trying the connection against "https://awx-host/[AWX-SLUG]"
Fixes: https://github.com/ansible/ansible-rulebook/issues/652
Jira: https://issues.redhat.com/browse/AAP-19726
Backport of https://github.com/ansible/ansible-rulebook/pull/654
> fix(backport): enable base_path for controller url (#654)

- CHANGELOG.md
- setup.cfg
Several fixes from drools ansible integration
https://issues.redhat.com/browse/AAP-19291
Backport from https://github.com/ansible/ansible-rulebook/pull/646
> feat(backport): upgrade to drools 1.0.6 (#646)

- ansible_rulebook/app.py
- ansible_rulebook/common.py
- ansible_rulebook/websocket.py
On the websocket channel previously we only supported sending tokens with this PR we can send a username and password from the eda-server. The username and password can be created in the RH AAP Credential Type.
https://issues.redhat.com/browse/AAP-22060
> feat: support controller username and password

- ansible_rulebook/app.py
- ansible_rulebook/util.py
- tests/unit/test_util.py
We were relying on checking if a string is decryptable by using substitution which causes issues when the data can contain data that will only be available when events are processed
Added a separate function called decryptable that can be called to check if the passed in 
* strings in extra vars if vaulted can be decrypted
* strings in action args if vaulted can be decrypted
source args are used at startup so that failure is seen right away
https://issues.redhat.com/browse/AAP-22487
This is part of the story where we want to catch decryption errors at startup so we don't have to wait for the rulebook to start executing and report decryption errors when running actions. https://issues.redhat.com/browse/AAP-19611
> fix: check if variables are decryptable outside of substitution

- CHANGELOG.md
- Dockerfile
Our [SQS Source plugin](https://github.com/ansible/event-driven-ansible/blob/7d84d9cca37428f6817da2bbc60c73d21672acbb/extensions/eda/plugins/event_source/aws_sqs_queue.py#L30) needs aiobotocore
https://issues.redhat.com/browse/AAP-23381
Fixed the Dockerfile to include the aiobotocore package
> fix: missing aiobotocore needed for SQS source plugin

- tests/e2e/utils/awx/readme.md
- tests/e2e/utils/awx/roles/install-awx/defaults/main.yaml
- tests/e2e/utils/awx/roles/install-awx/tasks/main.yaml
- increased the version of awx_operator_image_tag to 2.15.0 to fix error with Kustomize
- added a step specific for users of Podman
- increased the timeout for the cluster setup (I saw in testing that the default 120 seconds was not enough for a first install)
> Update E2E AWX test playbook and guide

- ansible_rulebook/rule_set_runner.py
Related: https://issues.redhat.com/browse/AAP-22056
Make it obvious that tasks are being cancelled when a source plugin shuts down (cleanup) or an error occurs while running the ruleset.
> feat: add terse but informative task cancellation message

- CHANGELOG.md
The version is already bump so we only need to update the changelog prior to tag and build the release.
> chore: update changelog for 1.1.0 release

- setup.cfg
pyyaml is a dependency from https://github.com/ansible/ansible-rulebook/pull/651/files#diff-1a9e40c0d3dc7e78f05263ea69bfd8e3ea9b2e3cdb0309da0c3f8a902adb4ff6R17
> chore: add missing pyyaml dependency

- .dockerignore
- Dockerfile
Update dockerfile to support openshift plus several minor improvements. 
- move from centos:stream9-development to centos:stream9 since the development image doesn't have up to date packages
- extend dockerignore
- remove unneeded asyncio package
- revisit and improve file permissions. 
Jira: https://issues.redhat.com/browse/AAP-24526
> chore: update dockerfile, support for openshift

- ansible_rulebook/rule_set_runner.py
If the action args contains an undefined variable we print the generic error returned by jinja:
`ansible_rulebook.rule_set_runner - ERROR - Error calling action debug, err 'dict object' has no attribute 'unexistent'`
Catch the exception to provide a little more descriptive of the issue:
`ansible_rulebook.rule_set_runner - ERROR - Undefined jinja variable  'unexistent' in action debug`
How to test:
```
- name: Ruleset 1
hosts: all
sources:
- ansible.eda.generic:
shutdown_after: 1
payload:
name: "Wilma"
rules:
- name: Run debug
condition: event.name == "Wilma"
actions:
- debug:
msg: "Event received, accesing unexistent key {{ event.unexistent }}"
```
> chore: improve error msg for jinja undefined action args

- CHANGELOG.md
- ansible_rulebook/websocket.py
Set the log level of websocket library to be ERROR since at DEBUG level it logs Authorization Headers leaking tokens
> fix: websocket logging

- CHANGELOG.md
- ansible_rulebook/action/run_job_template.py
- ansible_rulebook/action/run_workflow_template.py
- ansible_rulebook/cli.py
- ansible_rulebook/job_template_runner.py
- docs/actions.rst
- tests/test_controller.py
ansible-rulebook needs to be able to connect to 2.4 controller as well as the contoller in version 2.5 via the gateway
This is accomplished by the paths in the URL
If we need to talk to the 2.4 controller the URL is
* https://my_old_controller/
If we need to talk to the 2.5 contoller via Gateway the URL
* https://my_gateway/api/controller/
We append the slugs based on the presence of path
If the path is missing we append
* /api/v2/config
* /api/v2/unified_job_templates/
If the path is defined in the URL we append the following slug
* /v2/config
* /v2/unified_job_templates/
https://issues.redhat.com/browse/AAP-25509
> fix: switch slugs based on presence of path in controller url

- tests/test_controller.py
We have a global variable for job_template_runner which causes tests to fail intermittently. I have fixed only the ones that were broken on Mac.
> refactor: the controller tests were failing intermittently

- CHANGELOG.md
- ansible_rulebook/action/run_job_template.py
- ansible_rulebook/action/run_workflow_template.py
- tests/unit/action/test_run_job_template.py
- tests/unit/action/test_run_workflow_template.py
The JOB URL is going to be built on the server side since its difficult for the ansible-rulebook to convert an API end point to a URL. If the server has the controller_job_id and and the action type the server can build the URL.
https://issues.redhat.com/browse/AAP-25604
> fix: pass the controller job id to server via messages

- docs/rulebooks.rst
Update the documentation to expose this very hidden option.
> docs: update rulebooks.rst with missing ruleset option match_multiple_rules

- ansible_rulebook/rule_set_runner.py
https://issues.redhat.com/browse/AAP-28915
When doing performance testing the session stats after every action causes the DB to be updated. If we are skipping audit events we can send the session stats at the regular heartbeat interval and when the rulebook ends.
> fix: dont send session stats after every action when audit skipped

- docs/rulebooks.rst
match_multiple_rules has an inadvertent effect of leaving events in memory till the default_events_ttl expires.
> docs: notes for match_multiple_rules

- tests/e2e/test_run_module_output.py
- tests/examples/29_run_module.yml
- tests/examples/31_run_module_missing_args.yml
- tests/examples/32_run_module_fail.yml
- tests/unit/action/test_run_module.py
ansible.eda.upcase has been removed from the collection. Fix failed tests like [this one](https://github.com/ansible/ansible-rulebook/actions/runs/10451252336/job/28937289092) by using a standard ansible.builting.debug module.
> test: fix failed tests using ansible.builtin.debug module

- .github/actions/all-tests/action.yml
- .github/actions/common-tests/action.yml
- .github/actions/e2e-tests/action.yml
After further validation, we only need to be uploading test results from the main branch.
> fix: only upload on main branch

- docs/rulebooks.rst
This change aims to make it less confusing how the hosts: selector is used in rulebooks.
> Clarify how hosts: selector works in rulebook documentation.

- README.rst
- docs/contributing.rst
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
Thanks!
> Update community comms info

- CHANGELOG.md
- ansible_rulebook/action/helper.py
- ansible_rulebook/action/run_job_template.py
- ansible_rulebook/action/run_workflow_template.py
- ansible_rulebook/job_template_runner.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/actions.rst
- sonar-project.properties
- tests/examples/84_job_template_exclude_events.yml
- tests/examples/85_workflow_template_exclude_events.yml
- tests/examples/86_job_template_include_events.yml
- tests/examples/87_workflow_template_include_events.yml
- tests/examples/88_job_template_no_args.yml
- tests/test_examples.py
When we unconditionally send event data to the controller for a workflow template the launch of the workflow template fails. With this option in a rulebook the user can prevent event data from being sent by setting
- include_events: false
The default value is true so existing rulebooks will keep sending events to controller.
Fixes #622 
https://issues.redhat.com/browse/AAP-13456
Root Cause Analysis:
In the Controller if you are running a workflow template you cannot send event data to it unconditionally like we can do with job template. We get an error from Controller
**Check the Prompt on Launch setting on the Workflow Job Template to include Extra Variables.**
If a survey spec is involved then there are more constraints if there are certain parameters that are marked as required in the …
> feat: option to skip including events into extra_vars

- setup.cfg
Yesterday, 3.11 version of `aiohttp` was released with [breaking changes ](https://github.com/aio-libs/aiohttp/releases/tag/v3.11.0 ) which breaks `aioresponses` library used for our mocks and as consequence some of our tests are failing. 
Ref: https://github.com/pnuckowski/aioresponses/pull/262
Regardless of whether this is fixed in aioresponses, aiohttp can introduce breaking changes in minor versions, so I pin it to the latest tested version as this library is critical for the stability in some of our features.
> chore: pin minor version of aiohttp

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/common.py
- ansible_rulebook/websocket.py
- tests/data/test_cert.pem
- tests/data/test_env.yml
- tests/data/test_key.pem
- tests/test_websocket.py
AAP Credential Types support File contents via file injectors.
https://docs.ansible.com/automation-controller/latest/html/userguide/credential_types.html
We create temporary files with the data sent from Server The source plugin can access the temporary file names to access the data.
Supports single file as well as multiple files.
To access the filenames in the source rulebook you can use the following extra vars
- eda.filename or
- eda.filename.<<key_name1>>
- eda.filename.<<key_name2>>
e.g.
```
- name: Use payload file to check events
hosts: all
sources:
- ansible.eda.generic:
payload_file: "{{ eda.filename.test_payload_file }}"
```
The env variables are treated like extra_vars and added to the current processes environment
https://issues.redhat.com/browse/AAP-25519
> feat: support receiving file contents and env vars from EDA Server

- ansible_rulebook/action/run_playbook.py
- ansible_rulebook/util.py
- tests/e2e/files/inventories/inventory_as_dir/group_vars/customgroup.yml
- tests/e2e/files/inventories/inventory_as_dir/host_vars/localhost.yml
- tests/e2e/files/inventories/inventory_as_dir/hosts.yml
- tests/e2e/files/playbooks/print_group_vars.yml
- tests/e2e/files/rulebooks/test_inventory_as_dir.yml
- tests/e2e/test_actions.py
Fixes https://github.com/ansible/ansible-rulebook/issues/681
> fix: set correct inventory path when it is a dir

- tests/e2e/test_runtime.py
Fixed a broken test
https://github.com/ansible/ansible-rulebook/actions/runs/13295697912/job/37127030121
> chore: subprocess.signal.SIGINT missing in 3.12.9

- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/engine.py
- ansible_rulebook/json_generator.py
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/rules_parser.py
Calling ansible-vault as a separate process is a huge overhead and takes upto 2 seconds per variable. Doing this over and over before every substitution slows doen the entire processing. Now we decrypt once at startup and keep the decrypted values in memory and reuse them during substitution.
https://issues.redhat.com/browse/AAP-40490
> fix: decryption before every substitution disabled

- ansible_rulebook/cli.py
- tests/unit/test_cli.py
Keep similar with ansible/ansible-playbook's version output:
```
before:
$ ansible-rulebook --version
1.1.3
after:
$ ansible-rulebook --version
ansible-rulebook [1.1.3]
```
> chore: update get version output

- CHANGELOG.md
- ansible_rulebook/app.py
- tests/e2e/files/rulebooks/test_source_stacktrace.yml
- tests/e2e/test_source_stacktrace.py
- tests/sources/fail_after.py
A regular stack trace will print out args, data which can lead to security leak. So we want to limit the stack trace to just
* source file name
* function name
* line number
This will help users debug their source plugins etc, otherwise it would be very challenging where the code has issues
https://issues.redhat.com/browse/AAP-41261
> feat: log stacktrace with just file, function name and line number

- .readthedocs.yaml
Follow up https://github.com/ansible/ansible-rulebook/pull/755
We need to fetch the git history (by default rtd only fetches the branch without tags) as well as build the package prior to build the docs so the dynamic version can be processed. 
Also configures rtd to build the docs only if there are changes in the documentation
Demo: https://app.readthedocs.org/projects/ansible-rulebook/builds/27467234/
> docs: fix rtd builds for dynamic versioning

- .github/actions/common-tests/action.yml
- CHANGELOG.md
- ansible_rulebook/app.py
- ansible_rulebook/cli.py
- ansible_rulebook/collection.py
- ansible_rulebook/conf.py
- ansible_rulebook/util.py
- tests/e2e/test_operators.py
- tests/e2e/test_runtime.py
- tests/e2e/test_websocket.py
- tests/e2e/utils.py
- tests/unit/test_cli.py
- tests/unit/test_util.py
Print relevant versions in logs when ansible-rulebook starts in worker mode. 
- Refactor some helpers and ansible-galaxy path setting for reusability. 
- Enhance get_version function. 
- Collections are printed when debug enabled, regular versions only in info level. 
- e2e and unit tests. 
Jira: [AAP-40781](https://issues.redhat.com/browse/AAP-40781)
> feat: print relevant versions at worker startup AAP-40781

- tests/e2e/test_match_multiple_rules.py
- tests/e2e/test_non_alpha_keys.py
- tests/e2e/test_run_module_output.py
- tests/e2e/test_skip_audit_events.py
- tests/e2e/test_websocket.py
- tests/e2e/utils.py
We can have race conditions in some tests when running pytest with xdist (multiprocesses) with errors because the port is already in use. This ensures the port is different by adding the cpu core of the process.
> test: ensure multiprocess tests don't collision ports

- setup.cfg
Pin to version 10.4 to better align with downstream builds
> chore: pin to websockets 10.4

- requirements_test.txt
Pinning the version of marshmallow to account for pytest-jira failure when running tests.
https://github.com/rhevm-qe-automation/pytest_jira/issues/153
> test: pytest-jira failures due to marshmallow

- Dockerfile
- minimal-decision-environment.yml
- requirements_test.txt
In light of upcoming changes in ansible-core, pinning the version to 2.16 while we investigate the impact.
[AAP-43723](https://issues.redhat.com/browse/AAP-43723)
https://github.com/ansible/ansible/pull/84621
> chore: pin ansible-core to 2.16

- CHANGELOG.md
- setup.cfg
https://issues.redhat.com/browse/AAP-42623
Update to use the new version of drools_jpy, which contains the memory leak fix.
> fix: bump drools_jpy version to 0.3.10

- CHANGELOG.md
- setup.cfg
Brew build for drools_jpy is not ready yet, roll back the version
> fix: rollback drools_jpy version

- CHANGELOG.md
- setup.cfg
https://issues.redhat.com/browse/AAP-42623
Update to use the new version of drools_jpy, which contains the memory leak fix.
> fix: bump drools_jpy version to 0.3.10 again

- ansible_rulebook/cli.py
- ansible_rulebook/engine.py
- ansible_rulebook/exception.py
- tests/test_engine.py
subj: https://issues.redhat.com/browse/AAP-42108
This PR improves the missing source plugin error message, by modifying the message that is thrown by SourcePluginNotFoundException. Also, we prevent the error message from being spammed multiple times by ansible_rulebook.engine and ansible_rulebook.app and log the error message just once.
Before:
```
2025-04-28 14:50:35,653 - ansible_rulebook.engine - ERROR - Source error: SourcePluginNotFoundException: Source plugin failed with error message: 'Could not find source plugin for ansible.eda.non_existing_plugin. Please ensure that the appropriate Ansible collection is installed. If you're running from the CLI, you can use the -S option to specify additional source directories.'
2025-04-28 14:50:35,653 - ansible_rulebook.engine - ERROR - …
```
> refactor: improve missing source plugin exception message AAP-42108

- CHANGELOG.md
- ansible_rulebook/engine.py
- tests/examples/92_gather_facts_sans_inventory.yml
- tests/test_examples.py
backport https://github.com/ansible/ansible-rulebook/pull/810
gather_facts requires inventory, when running as CLI it always has inventory but when run as Activation the inventory is missing.
Ignore the gather_facts if no inventory is provided and print a warning message.
https://issues.redhat.com/browse/AAP-47846
> fix: gather_facts requires inventory (#810)

- CHANGELOG.md
Bump version for release 1.1.7 in changelog, backport of https://github.com/ansible/ansible-rulebook/pull/814
> chore: update changelog for 1.1.7 release (#814)

- setup.cfg
There was a memory leak in Drools ansible integration, the newer version of drools_jpy fixes that issue.
Upgrading to drools_jpy 0.3.12
https://issues.redhat.com/browse/AAP-46573
> fix: upgrade to newer drools which fixes memory leak

- ansible_rulebook/util.py
When the program is exiting in certain situations if the heartbeat task wakes up it will send an empty stats. By that point we have cleared the session stats in Drools.
https://github.com/ansible/ansible-rulebook/actions/runs/16843556694/job/47720246863?pr=826
> fix: race condition on exit while sending stats

- CHANGELOG.md
- ansible_rulebook/rule_set_runner.py
- ansible_rulebook/schema/ruleset_schema.json
- docs/actions.rst
- tests/examples/96_job_template_with_lock.yml
- tests/test_examples.py
When running the rulebook with the execution strategy set to parallel you can optionally specify a lock field to ensure sequential execution of a specific action.
The lock is currently supported for
* run_playbook
* run_module
* run_job_template
* run_workflow_template
There is no e2e test for this we will be adding an ATF test for this since it would be tested against the controller in the ATF.
https://issues.redhat.com/browse/AAP-51458
> feat: add lock support for certain actions

- ansible_rulebook/job_template_runner.py
- docs/actions.rst
- tests/test_controller.py
If the labels are resolved to be empty or None they will be skipped. Also if there are duplicate labels only one of them will be added.
https://issues.redhat.com/browse/AAP-52204
> fix: skip labels if empty string or None
