ansible/ansible-rulebook

pyproject.toml
setup.cfg

* Set max line length to 79 characters for flake8 and black.

Configure flake8 and black

---

ansible_events/engine.py
tests/sources/range.py
tests/sources/timestamp.py

Include some little syntax fixes raised by flake. Formatted with black according to the project config

Flake alignment

---

ansible_events/condition_parser.py
ansible_events/rule_generator.py
tests/test_conditions.py

Add support for or operator such as `condition: fact.i == 0 or fact.i == 1`

Add or operator

---

ansible_events/builtin.py
ansible_events/cli.py
performance_test/rules.yml
schema/ruleset_schema.json
tests/test_host_rules.yml
tests/test_kafka.yml
tests/test_rules.yml
tests/test_rules_multiple_hosts.yml

Changes argument name to be more consistent with the action name.

Changes argument for post_event to event

---

.editorconfig

add 2 spaces of indentation for yaml files in editorconfig.

add config for yaml in editorconfig

---

docs/multi_events.rst

https://issues.redhat.com/browse/AAP-3256
Some of the caveats mentioned in the docs will be worked
on in subsequent sprints

[AAP-3256] Added rst doc for multiple events

---

performance_test/sources/range.py

ERROR:root:Source error Entrypoint is not a coroutine function.
We had fixed this in tests/sources but not in preformance_test/sources

Fixed the source in performance_test to be asyncio compatible

---

tests/rules/test_host_rules.yml
tests/test_engine.py

The playbooks were not running because of host mismatch

Fixed test failures

---

ansible_events/drools/durable_rules_engine.py

Currently "emulated" via "assert_fact", the change at https://github.com/mariofusco/drools-yaml-rules/commit/b9ee5331e7a5bca9856b47507e10a3c58932cb19 ensures that the fact is actually being removed from the WM as soon as there is one match. We are also replacing the endpoint names to avoid confusion https://github.com/mariofusco/drools-yaml-rules/commit/03eb912d11e0b304e51b0281b2902c1937a29f9b
You can download the latest snapshot at (FIXED link) https://github.com/mariofusco/drools-yaml-rules/actions/runs/2876048896

Drools Support: Add support to post_event

---

Dockerfile

Install collection from git to ensure the latest version until have an automated publishing workflow for the collection

update collection install for dockerfile

---

ansible_events/app.py
ansible_events/builtin.py
ansible_events/cli.py
ansible_events/key.py
ansible_events/websocket.py

Supports [AAP-5269](https://issues.redhat.com/browse/AAP-5269)
Needed for https://github.com/benthomasson/ansible-events-ui/pull/74

Adds a worker mode to ansible-events to support container deployment

---

performance_test/100k_event_rules.yml
performance_test/10k_event_rules.yml
performance_test/1k_event_rules.yml

Changed + to is defined.
Left over from https://github.com/benthomasson/ansible-events/pull/151

Changed + to is defined in performance rules

---

ansible_events/app.py

Fixes https://issues.redhat.com/browse/AAP-5759 and https://github.com/benthomasson/ansible-events/issues/155

AAP-5759 fix error msg

---

ansible_rulebook/builtin.py

Reverts ansible/ansible-rulebook#184
I think this is causing tests to fail in #189 and #188

Revert "Limit to one artifacts folder for each playbook run"

---

ansible_rulebook/app.py
ansible_rulebook/cli.py
demos/sensu-kafka-demo/docker-compose.yml
docs/usage.rst
performance_test/run_perf.sh

Changed the command line option to load the rulebook from --rules to --rulebook

Changed cmdline --rules to --rulebook

---

tests/rules/test_empty_rule_names.yml
tests/rules/test_missing_rule_names.yml
tests/test_engine.py

Extend tests for https://github.com/ansible/ansible-rulebook/pull/185

Extend tests for rulenames

---

ansible_rulebook/builtin.py
tests/examples/38_shutdown.yml
tests/test_examples.py

fixes https://issues.redhat.com/browse/AAP-6303

AAP-6303 fix shutdown action and add test for it

---

docs/usage.rst

[AAP-6237:](https://issues.redhat.com/browse/AAP-6237)
Documentation: update docs/usage.rst

[AAP-6237]: Add ansible-rulebook CLI documentation

---

README.rst
docs/installation.rst

Updating installation instructions

---

.github/workflows/tests.yml
ansible_rulebook/builtin.py
ansible_rulebook/engine.py
ansible_rulebook/rule_generator.py
ansible_rulebook/rule_types.py
tests/test_conditions.py
tests/test_rules.py

This reverts commit 87be47ebde84da241d3e014ffe6ef6895854cd66.

Revert "Switch the default rules engine to Drools"

---

tests/asts/19_is_defined.yml
tests/examples/19_is_defined.yml
tests/test_examples.py

The is defined test now checks if the dictionary value is supported.
https://issues.redhat.com/browse/AAP-6388

[AAP-6388] Enhanced the test case for is defined

---

tests/sources/infrange.py

Improve infrange plugin to be able to generate a fixed sized random string in the event.

Extend infrange plugin to generate random data

---

.github/workflows/tests.yml
ansible_rulebook/builtin.py
ansible_rulebook/cli.py
ansible_rulebook/engine.py
ansible_rulebook/rule_generator.py
ansible_rulebook/rule_types.py
tests/test_conditions.py
tests/test_examples.py
tests/test_rules.py
tox.ini

closes https://issues.redhat.com/browse/AAP-7134

AAP-7134 add EDA prefix to environment variables

---

ansible_rulebook/builtin.py

After executing a playbook or module using the ansible runner we should delete the temporary directory.
https://issues.redhat.com/browse/AAP-5390

[AAP-5390] Remove the temporary directory

---

docs/authors.rst
docs/conf.py
docs/host_limit.rst
docs/index.rst
docs/installation.rst
docs/multi_events.rst
docs/multi_sources.rst
requirements_dev.txt

This PR updates the Sphinx configuration to use the Ansible theme. Also makes changes to remove warnings from docs build.

Docs: Ansible sphinx theme

---

ansible_rulebook/app.py

https://issues.redhat.com/browse/AAP-7755
If there is no websocket we dont have to create a asyncio Queue since no one is reading from it and it will keep growing
May help with
https://issues.redhat.com/browse/AAP-6289

[AAP-7755] Create NullQueue if no websocket address provided

---

docs/drools_seq.md

This uses the mermaid file format for sequence diagram

Added sequence diagram for Drools

---

docs/filters.rst
docs/index.rst
docs/rulebooks.rst

https://issues.redhat.com/browse/AAP-6238
Added a new rst file for rulebooks
Updated the filter documentation

[AAP-6238] Added docs for filters, rulesets and rulebooks

---

tests/e2e/files/rulebooks/websockets/test_websocket_range.yml
tests/e2e/test_websocket.py
tests/e2e/utils.py

Add E2E test for websocket
Depends on https://github.com/ansible/ansible-rulebook/pull/234
Closes https://issues.redhat.com/browse/AAP-7349

AAP-7349 Add e2e test for websocket

---

.github/workflows/tests.yml
ansible_rulebook/builtin.py
ansible_rulebook/cli.py
ansible_rulebook/engine.py
ansible_rulebook/rule_generator.py
ansible_rulebook/rule_types.py
tests/test_conditions.py
tests/test_examples.py
tests/test_rules.py
tests/unit/test_cli.py

We had switched from drools to durable_rules now switching it back to drools

Switch the default rules engine back to drools

---

ansible_rulebook/json_generator.py

Based on the comments in
PR https://github.com/ansible/ansible-rulebook/pull/247 Refactored the AST generator code.

Refactor AST generator code for drools

---

tests/sources/generic.py

Choose a fixed number of iterations, negative numbers create an infinite loop.

Choose number of loops for generic source plugin

---

tests/sources/generic.py

**create_index** : index_name   allows you to add a index to every event
The index starts at 0
**loop_delay**   : time         The delay between different iterations
This is different from the **delay** which is between events

Added additional options to the generic source for testing

---

.readthedocs.yaml
docs/actions.rst
docs/conditions.rst
docs/contributing.rst
docs/multi_events.rst
docs/requirements.txt
docs/rulebooks.rst
requirements_dev.txt

- Closes AAP-8329
- Add readthedocs config file
- Move docs requirements to the default path
- Some minor bugfixes in rst files.

AAP-8329 Fix readthedocs build

---

ansible_rulebook/app.py
ansible_rulebook/builtin.py
tests/e2e/test_operators.py

The strings can be quoted using the !r flag
https://github.com/PyCQA/flake8-bugbear check B028 description

Fixed the bugbear B028 lint warning

---

ansible_rulebook/condition_parser.py
ansible_rulebook/condition_types.py
ansible_rulebook/json_generator.py
tests/examples/49_float.yml
tests/test_ast.py
tests/test_examples.py

https://issues.redhat.com/browse/AAP-7962

[AAP-7962] Added support for Floats

---

ansible_rulebook/condition_parser.py
ansible_rulebook/condition_types.py
ansible_rulebook/json_generator.py
docs/conditions.rst
tests/examples/50_negation.yml
tests/test_ast.py
tests/test_examples.py

https://issues.redhat.com/browse/AAP-8092
e.g.
* not (event.i > 99)
* not event.some_boolean

[AAP-8092] Added support for negation

---

docs/actions.rst
docs/conditions.rst
docs/contributing.rst
docs/events_and_facts.rst
docs/getting_started.rst
docs/index.rst
docs/installation.rst
docs/introduction.rst
docs/sources.rst
docs/usage.rst

See https://github.com/ansible/ansible-rulebook/blob/main/docs/readme.md to get instructions about how check this PR. 
Includes:
- The introduction from the collection readme
- "Events and facts" section
- Supported datatypes
- Debug action updated
- Clarification about `not` operator
- Matrix chat link
- advices for development of sources
- Some format improvements

Extend documentation with more content

---

ansible_rulebook/cli.py
ansible_rulebook/util.py
docs/development_environment.rst
docs/installation.rst
tests/unit/test_cli.py

- Fix how the java version is acquired. 
- Ensure a valid JVM is installed
- Try to detect the default JVM install and set JAVA_HOME if necessary to improve the user experience. 
- Update docs accordingly
Resolves https://issues.redhat.com/browse/AAP-8667

AAP-8667 Fix and improve the JVM management

---

ansible_rulebook/util.py
tests/unit/test_cli.py

Minor fix in get_java_version
Update version string compatibility for macs
Add tests for check_jvm

Fix get_java_version and extend tests

---

.github/workflows/ci.yml
.github/workflows/scheduled.yml
requirements_lint.txt

Pin black version and fix CI job.

Pin black version

---

ansible_rulebook/engine.py

Pass in the event_log needed by https://github.com/ansible/ansible-rulebook/blob/main/ansible_rulebook/engine.py#L499

Fix a coding bug caused by a missing attribute

---

ansible_rulebook/builtin.py
ansible_rulebook/engine.py
ansible_rulebook/rule_generator.py
ansible_rulebook/rule_types.py
tests/e2e/test_actions.py

Remove unused facts in code

---

ansible_rulebook/condition_parser.py
ansible_rulebook/exception.py
ansible_rulebook/json_generator.py
tests/test_ast.py

https://issues.redhat.com/browse/AAP-8397
Added new exceptions for handling different kinds of condition parsing errors

Improve condition parsing errors

---

ansible_rulebook/engine.py
ansible_rulebook/job_template_runner.py
requirements_test.txt
tests/cassettes/test_job_template.yaml
tests/test_controller.py

This allows run_job_template action to run in parallel unconditionally
Also add a test to run lauch and monitor a job template execution
Resolves AAP-8991

Remove run_job_template from the queueable list

---

requirements_test.txt
tests/e2e/files/playbooks/run_playbook_test_playbook.yml
tests/e2e/files/rulebooks/actions/test_run_playbook.yml
tests/e2e/test_actions.py

Closes [AAP-8660](https://issues.redhat.com/browse/AAP-8660).

Adding e2e tests for run_playbook action

---

ansible_rulebook/condition_parser.py
ansible_rulebook/condition_types.py
ansible_rulebook/exception.py
ansible_rulebook/json_generator.py
tests/examples/49_float.yml
tests/test_examples.py

Used generic number format to support floats and integers which supports scientific notation.
https://issues.redhat.com/browse/AAP-9271

[AAP-9271] Add support for scientific notation

---

setup.cfg

Version 0.2.1
Bug Fixes:
https://issues.redhat.com/browse/AAP-9407
https://issues.redhat.com/browse/AAP-9282
https://issues.redhat.com/browse/AAP-9095
https://issues.redhat.com/browse/AAP-9365
https://issues.redhat.com/browse/AAP-9381

Adds newer version of drools_jpy

---

ansible_rulebook/builtin.py
ansible_rulebook/engine.py
docs/events_and_facts.rst
tests/asts/test_set_facts.yml
tests/e2e/test_actions.py
tests/rules/test_set_facts.yml

Also add ruleset and rule to extra_vars
Resolves AAP-8787

Remove facts and fact from extra_vars

---

ansible_rulebook/condition_parser.py
tests/test_ast.py

The select statement wasn't handling booleans correctly, it was being treated as a string.
https://issues.redhat.com/browse/AAP-9618

[AAP-9618] Fixed bug with booleans in select and selectattr

---

docs/conditions.rst
tests/e2e/files/rulebooks/operators/test_string_match.yml
tests/e2e/files/rulebooks/operators/test_string_search_regex.yml
tests/e2e/files/rulebooks/operators/test_string_search_search.yml
tests/e2e/test_operators.py

String search operators include search, match and regex (with negation)

Add e2e tests for string search operators

---

docs/rulebooks.rst

Remove link to examples

---

tests/e2e/files/extra_vars/test_variables_extra_vars.yml
tests/e2e/files/playbooks/print_rule_name.yml
tests/e2e/files/rulebooks/variables/test_variables_sanity.yml
tests/e2e/test_variables.py

Closes [AAP-8369](https://issues.redhat.com/browse/AAP-8369).

Adding e2e tests for variables

---

CHANGELOG.md
setup.cfg

version 0.2.3
Fixed the following issues
- selectattr operator with negation using greater/less than operators
- select operator and comparing ints and floats
https://issues.redhat.com/browse/AAP-9647
https://issues.redhat.com/browse/AAP-9616

Updated to use the newer drools_jpy

---

ansible_rulebook/schema/ruleset_schema.json
ansible_rulebook/validators.py

Fixes: https://github.com/ansible/ansible-rulebook/issues/397
Fixes: https://issues.redhat.com/browse/AAP-9747

Fix json schema and validate it at load time

---

tests/e2e/files/rulebooks/operators/test_select_operator.yml
tests/e2e/files/rulebooks/operators/test_selectattr_operator.yml
tests/e2e/test_operators.py

Closes [AAP-9057](https://issues.redhat.com/browse/AAP-9057).

Add e2e tests for select and selectattr operators

---

tests/e2e/config/default.yml
tests/e2e/files/rulebooks/actions/test_actions_sanity.yml
tests/e2e/test_actions.py
tests/e2e/test_variables.py

Closes [AAP-5634](https://issues.redhat.com/browse/AAP-5634).

Update actions e2e test to cover print_event with multiple events

---

tests/e2e/files/rulebooks/hello_events_with_var.yml
tests/e2e/test_runtime.py

- Fix bug with wrong rulebook name
- Use generic source plugin
- Update docstring

Update runtime RC check test

---

ansible_rulebook/app.py
ansible_rulebook/exception.py
tests/conftest.py
tests/data/rulebook.yml
tests/data/test_vars.yml
tests/test_app.py

Added missing tests for app.py

Cleanup: Add tests for app.py

---

CHANGELOG.md
ansible_rulebook/condition_parser.py
tests/examples/73_mix_and_match_list.yml
tests/test_examples.py

We had missed including booleans in a list
https://issues.redhat.com/browse/AAP-9794

[AAP-9793]: Added support for booleans in list

---

CHANGELOG.md
setup.cfg

https://issues.redhat.com/browse/AAP-9793
Bug fix, uprgaded to newer version of drools_jpy (0.2.4)

[AAP-9793]: Select was not working with null

---

tests/e2e/files/rulebooks/operators/test_logical_operators.yml
tests/e2e/files/rulebooks/operators/test_membership_operators.yml
tests/e2e/files/rulebooks/operators/test_relational_operators.yml
tests/e2e/files/rulebooks/operators/test_select_operator.yml
tests/e2e/test_operators.py

Closes [AAP-9448](https://issues.redhat.com/browse/AAP-9448).

Update e2e operator tests to test null operator

---

CHANGELOG.md
setup.cfg

https://issues.redhat.com/browse/AAP-9283
Updated to drools_jpy 0.2.5

[AAP-9283] Fixed a race condition in drools

---

README.rst
docs/getting_started.rst
docs/index.rst
docs/installation.rst
docs/introduction.rst

- Point users to readthedocs getting started page
- Minor grammar/formatting changes
- Remove references to eda-server

Update docs to improve installation experience

---

ansible_rulebook/cli.py

Remove double whitespace from shutdown help string

Remove whitespace from shutdown help string

---

.github/workflows/build-image.yml

Closes: https://issues.redhat.com/browse/AAP-9831

Add workflow to build the container image

---

tests/e2e/files/rulebooks/test_disabled_rules.yml
tests/e2e/test_runtime.py

Closes [AAP-9792](https://issues.redhat.com/browse/AAP-9792).

Add e2e test for disabled rules

---

ansible_rulebook/engine.py
ansible_rulebook/exception.py
tests/data/bad_source.py
tests/data/not_asyncio.py
tests/test_engine.py

- Changed Exception to custom exceptions
- Added tests

Added tests and exceptions for sources

---

tests/e2e/config/default.yml
tests/e2e/files/playbooks/long_running.yml
tests/e2e/files/rulebooks/actions/test_shutdown_graceful.yml
tests/e2e/files/rulebooks/actions/test_shutdown_now.yml
tests/e2e/files/rulebooks/test_process_sigint.yml
tests/e2e/files/rulebooks/test_process_source_end.yml
tests/e2e/test_actions.py
tests/e2e/test_runtime.py

Closes [AAP-9229](https://issues.redhat.com/browse/AAP-9229).
Also covered is concurrent execution of actions in the same, and different, rulesets. [AAP-6101](https://issues.redhat.com/browse/AAP-6101).

Adding e2e tests for shutdown action and process termination

---

tests/e2e/test_websocket.py

ProcessedEvent was removed in
PR https://github.com/ansible/ansible-rulebook/pull/296

Remove ProcessedEvent

---

CHANGELOG.md
ansible_rulebook/rule_set_runner.py
docs/rules.rst
tests/examples/59_multiple_actions.yml

Within a single rule if there are multiple actions they execute sequentially. Across multiple rules the actions still run in parallel.

[AAP-10135] Rules within an action run sequentially

---

ansible_rulebook/rule_set_runner.py

Some of the messages were confusion to users, these messsages help in debugging so changed its log level to debug
https://issues.redhat.com/browse/AAP-10182

[AAP-10182] Changed level of some log messages

---

ansible_rulebook/util.py
tests/unit/test_cli.py

Fixes https://github.com/ansible/ansible-rulebook/issues/455

Improve java version check to support invalid semantics

---

CHANGELOG.md
setup.cfg
tests/examples/74_self_referential.yml
tests/test_examples.py

https://issues.redhat.com/browse/AAP-10581
```
event.x == event.y
```
Needs a new drools_jpy == 0.2.8

[AAP-10581] Compare 2 different attributes in an event

---

ansible_rulebook/app.py
ansible_rulebook/cli.py
ansible_rulebook/websocket.py
docs/usage.rst
tests/test_websocket.py

The websocket url can be "wss" or "ws" if we are using self signed certs in dev mode we might need to disable certificate validation
https://issues.redhat.com/browse/AAP-11478

[AAP-11478] Added support for --websocket-ssl-verify

---

ansible_rulebook/rule_set_runner.py
tests/e2e/test_actions.py
tests/e2e/test_runtime.py
tests/e2e/utils.py

This was broken for multiple actions
https://issues.redhat.com/browse/AAP-11904

[AAP-11904] Fixed sequential execution for multiple actions

---

Makefile
docs/decision_environment.rst
docs/index.rst
minimal-decision-environment.yml
requirements_dev.txt

The starting point for documenting and support Decision Environment usage with a base DE.

Replace old Dockerfile with ansible-builder configuration

---

CHANGELOG.md

The CHANGELOG.md file has a new section for the future release

Reset the CHANGELOG.md for future release

---

docs/rules.rst

Removed unnecessary "or" in Example.

Removed unnecessary "or" in Example

---

.github/workflows/ci.yml
.github/workflows/e2e-tests.yml
.github/workflows/scheduled.yml
CHANGELOG.md
docs/installation.rst
pyproject.toml
setup.cfg
tox.ini

To be aligned with collection and rest of EDA requirements.

Remove support for python3.8

---

docs/decision_environment.rst

Fixed indents in  decision environment definition file examples.

Fixed indents in  decision environment definition file examples 

---

.github/workflows/ci.yml
.github/workflows/e2e-tests.yml.disabled

@Alex-Izquierdo proposing this as discussed per meeting on 2023-07-27
/cc @benthomasson @mkanoor

enable on PR CI for all tests, including long_run

---

.bumpversion.cfg
CHANGELOG.md
ansible_rulebook/__init__.py
setup.cfg

Bump version: 1.0.1 → 1.0.2

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/contributing.rst
docs/development_environment.rst
requirements_dev.txt

The commit messages have to conform to the conventional commit standard.
https://www.conventionalcommits.org/en/v1.0.0/

chore: add commitlint

---

tests/sources/range.py

* extra_payload
* str_enable
Are not used anywhere in the tests

refactor: removed unused options

---

docs/conditions.rst

https://issues.redhat.com/browse/AAP-14226

docs: handle ": " in a condition

---

tests/e2e/test_run_module_output.py
tests/e2e/utils.py

https://issues.redhat.com/browse/AAP-14735
Added e2e test for run_module

test: e2e test for run_module

---

.bumpversion.cfg
CHANGELOG.md
ansible_rulebook/__init__.py
setup.cfg

chore: change version for build to 1.0.3

---

CHANGELOG.md
setup.cfg

upgraded to 0.3.8 of drools_jpy

fix: bug fixes in drools

---

tests/unit/action/conftest.py
tests/unit/action/test_controller.py

Creating the Queue in the fixture seems to be causing an issue https://github.com/ansible/ansible-rulebook/actions/runs/7093631506/job/19307405050?pr=625

test: create the Queue in test

---

.github/workflows/build-image.yml
.github/workflows/ci.yml

Enable devel branch for workflows

ci: add devel branch to GH workflows

---

CHANGELOG.md
setup.cfg

Several fixes from drools ansible integration
https://issues.redhat.com/browse/AAP-19291

feat: upgrade to drools 1.0.6

---

.bumpversion.cfg
CHANGELOG.md
ansible_rulebook/__init__.py
setup.cfg

Backport of https://github.com/ansible/ansible-rulebook/pull/661

chore: bump to version 1.0.5 (#661)

---

docs/introduction.rst

As per request from @josephpisciotta

docs: remove office hours section

---

.bumpversion.cfg
CHANGELOG.md
ansible_rulebook/__init__.py
setup.cfg

jira https://issues.redhat.com/browse/AAP-20807

chore: bump to 1.0.6

---

tests/test_token.py

The test should not connect to a real url but mock the connection properly

fix: test_renew_non_json_body not connect to a real url

---

docs/conditions.rst
docs/filters.rst

Cleaned up some stray `make html` docs build warnings.

Fix build warnings

---

docs/getting_started.rst

just another tidy-up on the docs.

docs: copy-edit of getting started guide

---

docs/getting_started.rst
docs/installation.rst

Just a copy-edit and a bit of clarification on the container image option so it's clear that it doesn't need the requirements section that is really only for the pip installs.

docs: Minor tidying up of install docs

---

ansible_rulebook/websocket.py

AAP-27738: websocket fails to reconnect to restarted eda-server
image to test: quay.io/bilwei/ansible-rulebook:ws6

fix: catch more websocket connect exceptions

---

CHANGELOG.md
docs/conditions.rst

Also fixed some spelling mistakes

docs: typos in matching events

---

.github/workflows/ci.yml
.github/workflows/scheduled.yml
setup.cfg
tests/e2e/files/rulebooks/test_hot_reload.yml
tox.ini

Adds support for python 3.12. 
Also updates a test with a race condition in 3.12

chore: add support for python 3.12

---

.bumpversion.cfg
ansible_rulebook/__init__.py
setup.cfg

Updates ansible-rulebook version to 1.1.2

chore: update to version 1.1.2

---

demos/sensu-kafka-demo/docker-compose.yml
demos/sensu-kafka-demo/sensu-cli/Dockerfile

replace all docker references with gcr mirror

chore: remove docker

---

.bumpversion.cfg
CHANGELOG.md
ansible_rulebook/__init__.py
ansible_rulebook/app.py
ansible_rulebook/cli.py
ansible_rulebook/engine.py
ansible_rulebook/json_generator.py
ansible_rulebook/rule_set_runner.py
ansible_rulebook/rules_parser.py
demos/sensu-kafka-demo/docker-compose.yml
demos/sensu-kafka-demo/sensu-cli/Dockerfile
setup.cfg
tests/e2e/test_runtime.py
tests/unit/test_cli.py

This is a rebase from main after diverge in  https://github.com/ansible/ansible-rulebook/pull/726 and https://github.com/ansible/ansible-rulebook/pull/727  
From now, any later rebase should not have conflicts, we will still see issues regarding cherry picked commits. 
MUST BE REBASED, not squashed

chore: Update stable 1.1 with latest main

---

ansible_rulebook/cli.py
docs/usage.rst

- update the CLI help text
- update the usage doc

chore: update argument help text

---

docs/development_environment.rst

add hyperlink for pytest, flake8, tox

docs: update hyperlink in doc

---

docs/installation.rst

docs: update macOS installation

---

.github/workflows/release.yml

Add a workflow to automate the build and publishing of a new release. 
Jira: https://issues.redhat.com/browse/AAP-41583

ci: add release workflow AAP-41583

---

ansible_rulebook/cli.py
docs/usage.rst

- improve `--id` and `-S` help desc

chore: help desc improvement

---

ansible_rulebook/rule_set_runner.py
ansible_rulebook/util.py
tests/e2e/files/extra_vars/test_debug.yml
tests/e2e/files/rulebooks/test_debug_no_params.yml
tests/e2e/files/rulebooks/test_debug_var_and_message.yml
tests/e2e/test_runtime.py
tests/examples/91_mask_senstive_variables.yml
tests/test_examples.py
tests/unit/test_util.py

Minor linting and refactoring changes

chore: minor refactor

---

setup.cfg

Pins websockets >=10.4,<12 to be consistent in our release process

Pin websockets

---

ansible_rulebook/websocket.py

Fix a bug introduced by https://github.com/ansible/ansible-rulebook/pull/763 that prevents ws connections.

fix: fix url for websocket ssl context

---

ansible_rulebook/cli.py
ansible_rulebook/engine.py
ansible_rulebook/exception.py
docs/actions.rst
tests/test_engine.py

This is a routine backport to stable-1.1 from main. No plan to make a new release to pypi yet.

dump main on stable1.1

---

ansible_rulebook/websocket.py
setup.cfg
tests/e2e/test_match_multiple_rules.py
tests/e2e/test_non_alpha_keys.py
tests/e2e/test_run_module_output.py
tests/e2e/test_skip_audit_events.py
tests/e2e/test_websocket.py
tests/e2e/utils.py

Tehcnical debt, upgrading to the latest version of websockets
https://websockets.readthedocs.io/en/stable/howto/upgrade.html
https://issues.redhat.com/browse/AAP-44207
The new websockets RPM is being tracked in https://issues.redhat.com/browse/AAP-44222

fix: upgrade to the latest websockets
